### ISSUE TITLE
URGENT Fully Qualified Domain Names (FQDNs) all internal services to service.librerouter.net

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#100]
Configure internal dns and nginx to be with this domains format.

**Comment by k1ktr0n** [comment]
Please generate the CSR:

openssl req -new -newkey rsa:4096 -nodes -out storage_librerouter_net.csr -keyout storage_librerouter_net.key -subj "/C=CH/ST=6300/L=Zug/O=Librerouter/OU=Technical/CN=storage.librerouter.net"

**Comment by nikdavnik** [comment]
generated 
[Storage_librerouter.zip](https://github.com/Librerouter/Librekernel/files/560109/Storage_librerouter.zip)
