### ISSUE TITLE
11 URGENT  Implement ssh as hidden service in TOr and i2p also implement outgoing SSH to be tunneled via ndpi and iptables

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#112]
URGENT outgoing SSH:

ssh-to onion-->-resolves IP onion unbound-->ndpi detects ssh payload-->redirects to socks port in TOR

URGENT Incoming hidden service:

SSH server<---Hidenservice redirect destination 22 of the onion<--TOR traffic
http://www.nurdletech.com/linux-notes/ssh/hidden-service.html

**Comment by nikdavnik** [comment]
SSH as a tor hidden service have been implemented.
Now I am working on outgoing SSH implementation

**Comment by nikdavnik** [comment]
ssh through tor have been implemented.
Now I work on i2p part

**Comment by k1ktr0n** [comment]
did you tested? how

**Comment by nikdavnik** [comment]
how? 
we have 4-5 librerouters. I can do test from one librerouter to another.

I connected linux machine to librerouter1 as a client.
then in terminal 
ssh user@sshoniondomain.onion  

 (sshoniondomain.onion is ssh hidden service in librerouter2, and librerouter1 and librerouter2 are in different networks).

**Comment by pastafaarian** [comment]
screen shot please when you implement or test things keep evidence with insights here

**Comment by k1ktr0n** [comment]
tested? paste evidence screenshot

**Comment by orwellencarnation** [comment]
david any update of the evidence?

**Comment by nikdavnik** [comment]
![ssh](https://cloud.githubusercontent.com/assets/17772064/21458642/b356ecb0-c951-11e6-8c42-f00669869a36.png)

**Comment by nikdavnik** [comment]
you can test it. Connect linux machine(will be more easy that windows) to your librerouter as a client machine, then from that cilent to ssh connection to any other librerouter
