### ISSUE TITLE
Configuration script's "UNKNOWN PLATFORM" Error.

### ISSUE THREAD

**Issue by samy-mohsen** [Librerouter/Librekernel#113]
@SibirskiyVolk 

Evidence of the incident:

![librerouter-config](https://cloud.githubusercontent.com/assets/22909056/19945786/4f4e5124-a14a-11e6-8a34-a8996f722882.png)

Happened after trying to run librerouter-config script after booting the system.

**Comment by SibirskiyVolk** [comment]
Fixed on build server, next build should have this cleared
