### ISSUE TITLE
Error extracting domain list.

### ISSUE THREAD

**Issue by samy-mohsen** [Librerouter/Librekernel#115]
@SibirskiyVolk @nikdavnik 

Evidence of the issue:

![domain](https://cloud.githubusercontent.com/assets/22909056/19947171/9608fa42-a14f-11e6-93ad-65fa2caaec53.png)

Can't tell if this is an iso related problem or a config. script related problem.

**Comment by SibirskiyVolk** [comment]
Can you install latest version of David's script on a Debian jessie "not the iso" and confirm if exists?

**Comment by samy-mohsen** [comment]
I tested it on a fresh Debian installation and the issue is not present.

**Comment by nikdavnik** [comment]
this have been fixed. Please close
