### ISSUE TITLE
implement something like this curl -s https://miniurl/setup.sh | sudo bash

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#117]
curl -s https://miniurl/setup.sh | sudo bash
miniurl =github url 
setup.sh that run app installation and app configuration together

**Comment by nikdavnik** [comment]
Implemented.
It's can be runned by 
curl -s https://raw.githubusercontent.com/Librerouter/Librekernel/gh-pages/setup.sh | bash

**Comment by k1ktr0n** [comment]
create a mini url

**Comment by nikdavnik** [comment]
created 
wget http://bit.ly/2gbKstn | bash 2gbKstn

**Comment by k1ktr0n** [comment]
ITs not working! please test shit before comit and close

**Comment by k1ktr0n** [comment]
is not working, why you dont test before asuming resolved?

**Comment by k1ktr0n** [comment]
404 not found

**Comment by nikdavnik** [comment]
try this, I missed -L option
curl -L http://bit.ly/2gbKstn | bash

**Comment by k1ktr0n** [comment]
this is working but i need to test if really the automated reboot helps
