### ISSUE TITLE
The script does not show addresses of new services and should include more stuff

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#120]
Should show also the mounts if second harddisk and the directory patch of the moved owncloud and tahoe lafs.

**Comment by nikdavnik** [comment]
tract,redmine,gitlab onion addresses have been added

**Comment by k1ktr0n** [comment]
tested from tor and i2p?

**Comment by nikdavnik** [comment]
i2p and tor addresses have been aded
