### ISSUE TITLE
ntop is not working and neither NTOP VERSION IS NOT LATEST WITH LATEST ndpi

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#126]
Ntop config is wrong
Ntop user and password for config is wrong
Ntop should have preconfigure to monitor all interfaces especially LAN WAN
NTOP SHOULD NOT BE BIND TO EXTERNAL WAN IP

**Comment by k1ktr0n** [comment]
NTOP VERSION IS NOT LaTEST WITH LATEST ndpi

**Comment by nikdavnik** [comment]
ndpi version is the latest 1.8
ntop latest version is ntopng, I will commit it soon

**Comment by k1ktr0n** [comment]
ok when

**Comment by nikdavnik** [comment]
ntopng is implemented

**Comment by pastafaarian** [comment]
screenshot please when you implement or test things keep evidence with insights here

**Comment by k1ktr0n** [comment]
any update? will team  files and logs?

**Comment by nikdavnik** [comment]
![ntop1](https://cloud.githubusercontent.com/assets/17772064/20814409/ef619e92-b832-11e6-8b61-f830c7f11a5d.png)
![Uploading ntop2.png…]()

**Comment by nikdavnik** [comment]
![ntop2](https://cloud.githubusercontent.com/assets/17772064/20814433/0935d356-b833-11e6-8f07-f19db3af0468.png)
