### ISSUE TITLE
9 urgent banks in spain are not being bump bypassed for example the one we add lacaixa.es

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#127]

**Comment by k1ktr0n** [comment]
put the results of murtaza script in acl do script take murzata output file of the ips in the iptables acls prepare

**Comment by nikdavnik** [comment]
bybassing works wine for ip addresses we have already added.
For lacaixa.es, I assume that we didn't have it, or its ip address have been changed.

Bypassing for ip addresses (4-5) we have now is working fine. When I receive addresses from Murtaza script I will add all of them to be bypassed

you can close this issue

**Comment by orwellencarnation** [comment]
Add to
