### ISSUE TITLE
CRITICAL if cable disconects then interface internal is down as well subinterfaces place here evidence of cron fix

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#128]
The interface internal took a dhcp ip from HIS OWN DHCP SERVER!

**Comment by k1ktr0n** [comment]
David where is the evidence of the CRON sanity interface checks?

**Comment by nikdavnik** [comment]
Now cron is doing check after reboot. I need to find way to do checks when cable is reconnected

**Comment by nikdavnik** [comment]
we added link to interface_checking script into /etc/network/if-post-down.d, so script will run when interfaces goes down
