### ISSUE TITLE
Explain why this ports are published in the WAN they shouldNT

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#129]
In the WAN IP (dinamic usually)
88 apache
111 rpcbind
NTOP 3000
Squid 3128
8080 apache
8090 jetty
8443 no idea
8888 tiniproxy -should be inside

Port that should be:
25
IMAP
22
POP
VoIP udp hole punching
DNS
This need to be published in the client internet router via PLUNGNADPLAY or PMPT

**Comment by nikdavnik** [comment]
duplicate #139

**Comment by nikdavnik** [comment]
at this moment we have in WAN side
22/tcp     ssh
25/tcp     smtp
8443/tcp  easyrtc
8090        yacy
