### ISSUE TITLE
URGENT FIX HTTPS

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#13]
HTTPS need to be fixed>
a) First allowing direct traffic to internet NOT throught tor
b) After doing SSLbumping in all SSL whatever is dark or clearnet and applying AntiVirus and Surikata and Snort.

**Comment by k1ktr0n** [comment]
https://github.com/dani87/sslbump
clamav for https: https://www.google.de/search?q=clamav+squid+ssl

**Comment by nikdavnik** [comment]
SSL bumping is configured.
For this squid 3.4.13 has been builded with --enable-ssl option.
Now squid listens for https requests in port 10.0.0.1:3131

**Comment by nikdavnik** [comment]
Https traffic is going through squid with ssl-bumping. https traffic is being decrypted and scaned by calmav,

**Comment by nikdavnik** [comment]
Https ssl bumping is implemented.
For snor and suricata implementation we have other opened issues (#49). SO this issue can be closed.
