### ISSUE TITLE
remove rpcbind 

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#135]

**Comment by k1ktr0n** [comment]
https://blog.binarymist.net/2014/12/27/installation-hardening-of-debian-web-server/

**Comment by nikdavnik** [comment]
removed

**Comment by k1ktr0n** [comment]
why you close with no comments crazy?

**Comment by nikdavnik** [comment]
I added removal in installation script. When installation script finishes, it will remove rpcbind from machine
