### ISSUE TITLE
4 CRITICAL VERY URGENT implement upnp to wan ports allowed and add all services in services comand.

### ISSUE THREAD

**Issue by nikdavnik** [Librerouter/Librekernel#138]
https://github.com/kinkome/pipe2me PLEASE IMPLEMENT AND DO PORTS PUBLISHED IN WAN TO BE ALSO REPUBLISHED IN OWNERS INTERNET ROUTER
 
5) Anything that is not the published ports from WAN and upnp mapped in Internet router is not allowed examples: email 25 to postfix, dovecot, roundcube web, dyndns solution (other issue for implementation), proxy encryption glype, voip xmpp or owncloud.

**Comment by nikdavnik** [comment]
points 1-6 have been configured

**Comment by k1ktr0n** [comment]
https://github.com/kinkome/pipe2me for publishing in router internet the nated for necesary or you want to use any other upnp program?
need to be opened in internet
prosody federation
25 postfix
glype
posibly others like tor 
yacy p2p
please assest

**Comment by orwellencarnation** [comment]
glype service is not shown in command services pipe2me is not implemented and need to be

**Comment by orwellencarnation** [comment]
EVIDENCE PLEASE GUYS IF YOU TESTED

**Comment by orwellencarnation** [comment]
Whi is taking this?

**Comment by orwellencarnation** [comment]
ANY FUCKING PROGRESS AFTER 2 MONTHS!
