### ISSUE TITLE
DAVID URGENT : porno reason block from ecapguardian N/a improper cathegory

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#142]

**Comment by k1ktr0n** [comment]
any update? will team document ecapguardian config files and logs?

**Comment by nikdavnik** [comment]
Fixed. Cathegory "Pornography" added
![ecap](https://cloud.githubusercontent.com/assets/17772064/22223497/afdee57e-e1d4-11e6-8c12-1f307a3fb084.png)

**Comment by orwellencarnation** [comment]
I will double check when I can test the scripts...
