### ISSUE TITLE
7 urgent  direct url address in services command do not show service correct fqdn

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#144]
Why services is showing old service url and not service.librerouter.net ?
its showing service.librenet

**Comment by nikdavnik** [comment]
direct urls have been changed for
conference.librerouter.net
search.librerouter.net
email.librerouter.net
storage.librerouter.net
social.librerouter.net

we also have
trac.librenet
redmine.librenet
gitlab.librenet

**Comment by nikdavnik** [comment]
redmine, trac and gitlab also have been changed to name.librerouter.net

This issue can be closed

**Comment by orwellencarnation** [comment]
include the rest of all services like ntop and so on.

not all the services need to be in tor only services but not ntop or suricata gui. or modsecurity or squidgurad gui
