### ISSUE TITLE
15 urgent: ssl bumping not doing certificate mimicking open issue in expert from squid.

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#153]
http://wiki.squid-cache.org/Features/SslPeekAndSplice
Mention freelance or contract b2b mode for help

rousskov@measurement-factory.com
squid3@treenet.co.nz
steve@opendium.co
yvoinov@gmail.com
support@diladele.com

**Comment by nikdavnik** [comment]
![cert_google_ok](https://cloud.githubusercontent.com/assets/17772064/23380749/6f48e2ac-fd55-11e6-8cd7-6bab17de74d2.png)
![cert_google_error](https://cloud.githubusercontent.com/assets/17772064/23380754/73326780-fd55-11e6-9b3a-8bddb40ffabe.png)

Certificates atributes are being mimicked and are same us original and mimicked certificates.
CommonName
OrganizationName
LocalityName
StateOrPrivinceName
CountryName

The One difirence in certificates is issuer part.
Squid mimicked certificates are being signed by "Internet Widgits Pty Ltd" which is unknown issuer for mail browsers

**Comment by orwellencarnation** [comment]
Please open the certificate in the brouswer of the client and see the domain and properties.
