### ISSUE TITLE
14 urgent squidguard ecapguardian do not work in https diladele yes with icap could you check if true?

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#154]
Filter SSL Encrypted HTTPS Web Traffic

Web Safety is an ICAP server integrated with Squid Web Proxy. This deployment scheme allows for extended filtering and deep inspection of SSL encrypted web traffic. With properly configured Squid and client certificates in the browsers HTTPS enabled sites are filtered and prohibited content is blocked just like normal HTTP. Other widely available open source web filtering solutions like Dansguardian or SquidGuard lack this functionality.

**Comment by nikdavnik** [comment]
Ecapguardian is blocking https site very well.
Here is the test result (https://porn.com have been blocked with category pornography)

![ecapblocking](https://cloud.githubusercontent.com/assets/17772064/23183449/8223f5ac-f895-11e6-9ce7-a8b1a696f8cd.png)

Also I did some investigations, diladele works in same way as ecapguardian. Its getting decrypted http traffic (not https) from squid, like our ecapguardian in our librerouter.
The one advatage from diladale is web configuration interface
