### ISSUE TITLE
DAVID URGENT Open support case in both github,bountycode and emails for the NDPI  for kernel panic.

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#156]
betolj@gmail.com
eliezer@ngtech.co.il
support@ntop.org
deri@ntop.org
campus@ntop.org
theirix@gmail.com
alexis.lagoutte@gmail.com
lorenzo.mangani@gmail.com
gklipel@gmail.com
https://github.com/ntop/nDPI   not in the other you did david

**Comment by nikdavnik** [comment]
I found already opened issue in github for kernel panic.
There is a suggestion to use other repository https://github.com/vel21ripn/nDPI, which does not panic. 
I am working on it, will update soon

**Comment by orwellencarnation** [comment]
paste the proper link

**Comment by nikdavnik** [comment]
I installed new version of ndpi from https://github.com/vel21ripn/nDPI,
it seems working fine,

will test few more days and post results

**Comment by nikdavnik** [comment]
new ndpi seems does not panic. I updated scripts to new one.

**Comment by orwellencarnation** [comment]
evidence that tested and works

**Comment by nikdavnik** [comment]
Here is some kind of evidance
![ndpi](https://cloud.githubusercontent.com/assets/17772064/22264751/850f40be-e292-11e6-868a-4d134b2f7707.png)

At first I added rule in librerouter iptables to block all ssh traffic by ndpi --ssh protocole (right terminal)
ant tried to connect to router by ssh port 222, and as you can see connection got refused.

Then I deleted ndpi --ssh blocking rule from librerouter and again tried to connect to librerouter by port 222 and connection goes.

So ndpi is working and its able to detect traffic by protocole (not by port)
