### ISSUE TITLE
2 extremelly urgent fix curl for wget  and setup.sh

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#159]
Why app configuration start do not check that app installation didi ran when you use setup.sh?
In librerouter do all logs after installation are sent upload to a ftp server.Including screen and not screen logs

**Comment by nikdavnik** [comment]
use this one
wget -O - http://bit.ly/2gbKstn | bash

**Comment by orwellencarnation** [comment]
NOT WORKING missing url

**Comment by orwellencarnation** [comment]
test your self before to write
