### ISSUE TITLE
2 extremelly urgent if configuration script detect that exist at least 1 interface wlan 

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#160]
Bind this WLAN the bridge of LAN  as it was in the past.
Check if the wlan interface support ap mode.
Setup ap mode of this wireless interface. # apt-get install hostapd
configure it inside LAN brige to serve dhcp fom LAN
Generate random ap name and pass
Show them in service.sh command script.
As should bridge with LAN the DHCP server should server IPs in the WLAN please test,

Step #2: Configure hostapd

Edit /etc/default/hostapd, enter:
# vi /etc/default/hostapd

Uncomment and set DAEMON_CONF to the absolute path of a hostapd configuration file and hostapd will be started during system boot:

DAEMON_CONF="/etc/hostapd/hostapd.conf"

Save and close the file. Next create a text file called /etc/hostapd/hostapd.conf, enter:
Set interface name:

### Wireless network name ###
interface=wlan0
 
### Set your bridge name ###
bridge=br0

**Comment by JFrancoJ** [comment]
Only if USB wlan device ? 
Or  always where the public NATED is not on not used on unique wlan or extra wlan is available ? 
I .e eth0->router dhcp->internet + wlan0 
      eth0 ->router dhcp-internet + eth1 ->dhcp->private lan + wlan0 AP->dhcp->private_lan
      wlan0->router dhcp->internet + wlan1 AP
