### ISSUE TITLE
1 extremelly urgent services must show complete set of services.

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#161]

**Comment by nikdavnik** [comment]
We have the following services in "services" command, what else to add?
mysql
postfix
easyrtc
friendica
gitlab
mailpile
owncloud
redmine
trac
yacy
ssh
roundcube
webmin

**Comment by orwellencarnation** [comment]
All runinglike snort guis from posfix alll, so. Create a list

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique

**Comment by mogolo** [comment]
Surikata,postfix admin,  giu from modsecurity, doba l:st of Ll runi g

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique

**Comment by nikdavnik** [comment]
surikata gui - kibana.librerouter.net  - added
postfixadmin - postfix.librerouter.net  - added
NTOP - ntop.librerouter.net  - added
GLYPE - glype.librerouter.net - added
