### ISSUE TITLE
0 MOST URGENT Modify both script to write the output when they executed properly or not both

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#162]
Modify both script to write the output when they executed properly or not both

Create list of logs files from all engines take all logs files from all engines in a list called logs.sh
make a logs script that when executed Noted the amount of size of all the changes in realtime.

list of all configuration files for all engines. show up in a script like services called configs.sh

**Comment by nikdavnik** [comment]
Scripts execution logs have been implemented
after scripts execution you can find logs in /var/libre_install.log and /var/libre_config.log

I added "logs" and "configs" commands to show engines logs and configuration files locations
