### ISSUE TITLE
mailpile gpgerror

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#167]
Acquire::https::dl.dropboxusercontent.com::Verify-Peer \"false\";
    Acquire::https::deb.nodesource.com::Verify-Peer \"false\";
        " > /etc/apt/apt.conf.d/apt.conf

    error de validacion de la PGP al verificar dl.dropboxusercontent.com

- CRITICAL
  Installing mailpipe: "Can not roll back crypto ..."

**Comment by JFrancoJ** [comment]
How to fix it:
Add "apt-get -y libffi-dev" on top of Mailpile installation.
Tested on Debian 8.6.0 amd64

**Comment by nikdavnik** [comment]
updated, thank you
