### ISSUE TITLE
CRITICAL DHCP SERVER WORKING/serving/leasing  IN WAN PORT   should be only in LAN

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#168]

**Comment by nikdavnik** [comment]
here is the network our dhcp server is listening
**subnet 10.0.0.0 netmask 255.255.255.0**

In my librerouter there is no dhcp in WAN side, I need to investigate our machine to find out whats wrong

**Comment by JFrancoJ** [comment]
Mine is listening on all interfaces, even the wan is on other IP range.
I read other people facing same issue even the dhcpd is configured and expected to listen only if the 
interface has some IP in the range.
I tried RH style on dhcpd.conf but doesn't works ( like dhcpd_iface="eth1" )
Then I tried with iptables to drop udp ports 67:68 packets on wan iface and was fine.
My lab is Debian 8.6.0 amd64

**Comment by orwellencarnation** [comment]
David any sugestion, I would NOT like to make it via IPtables because 
WAN is taken the IP via dhcp client

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique

**Comment by nikdavnik** [comment]
fixed
