### ISSUE TITLE
ISSUE sysctl hardening configuration

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#175]
http://linoxide.com/how-tos/linux-server-protection/

**Comment by geobarrod** [comment]
I create a bash script that solves some points in the link above.

Tested in:
Linux librerouter 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
Release: 8.7
Codename: jessie

1. Remote access configuration. (Resolved complete).

2. Narrow down permissions (Resolved, minus the following):
/var/log/audit: No such file or directory *
/etc/rc.d/init.d/iptables: No such file or directory *

3. Tune kernel parameters (Resolved, minus the following):
/proc/sys/kernel/exec-shield: No such file or directory *
/proc/sys/net/ipv4/icmp_ignore_bogus_error_messages: No such file or directory *
/proc/sys/net/ipv6/conf/all/send_redirects: No such file or directory *

5. Security Enhaced Linux - SELinux (SELinux was substituted by AppArmor) *

6. Setup IPTABLE rules (Pending) *
What unwanted ports?
What bad IP's?

7. Verifying file system (Pending) *
Only identify and show unwanted SUID and SGID binaries?
Only identify and show world writable files?
Only identify and show orphaned files and folders?

---
(*) The function was excluded from script

**Comment by geobarrod** [comment]
Check the implementation here https://github.com/geobarrod/Librekernel/commit/a2c4ef6dfcddf82d3fa63e983c662249ae8ed8a4
