### ISSUE TITLE
Luis Narvaez app'configuration'script line 326 fail command not found.

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#186]
Why appconfiguration script runs before app0-installationscript?
And apart of this error of setup.sh
In app-configurationscript , why you didnt moved wlan stauff to last part of the script?

Why this WLAN do not support ap mode? Im pretty sure this support AP mode.
And why command not found.

**Comment by orwellencarnation** [comment]
Separate wlan ap mode script to a separate one
Start to add menu to services.sh and add  option to execute wlan client and apmode from there

**Comment by orwellencarnation** [comment]
you separated?

**Comment by nikdavnik** [comment]
seperated.

Created apmode.sh file
added new feature in services command to run apmode.sh and select mode

root@librerouter:~/librekernel# services

    Usage: services  [OPTION]

    -p   print servicese information
    -w   run wlan AP configuration
    -h   print help

**Comment by luisnarvaez19** [comment]
The script no longer fails on this line. The problem was that if the WLAN does not exist the script fails

**Comment by luisnarvaez19** [comment]
Issue 186 ready. Can be closed
