### ISSUE TITLE
David            Mailpile python app-installtionscript stoped

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#190]

**Comment by nikdavnik** [comment]
in my librerouter sogo installation is ok. I need to check your machine to find the problem
![sogo_apt](https://cloud.githubusercontent.com/assets/17772064/22218307/a19e5a72-e1bf-11e6-863f-1b0392ff82f9.png)

**Comment by mogolo** [comment]
because your not using latest debian version 64b

**Comment by fjmz** [comment]
At the moment fixed on Debian/Ubuntu, I'm downloading Trisquel (now) for test and implement it.

**Comment by orwellencarnation** [comment]
forgot trisquel, here is only debian

**Comment by orwellencarnation** [comment]
Updating repositories packages ...
W: GPG error: https://dl.dropboxusercontent.com wheezy InRelease: The following signatures were invalid: KEYEXPIRED 1460252357
Installing packages ...
E: Unable to locate package sogo
Error: unable to install packages
Erron in installtaion script. Exiting ...
root@debian:/home/x# ^C
root@debian:/home/x#

**Comment by orwellencarnation** [comment]
Im testing with wget -O - http://bit.ly/2gbKstn | bash
that uses setup.sh
that download app-installation-script.sh

**Comment by fjmz** [comment]
Sogo installs correctly, I added the repository 'nightly', Are you sure I downloaded the modifications I made? I just tried it on a virtual machine I have. (Clean Installation)

I Attach screenshot with a example.
![sogo-debian8](https://cloud.githubusercontent.com/assets/24794596/22261307/b346dbf2-e26c-11e6-8d3a-7c10bad5740e.jpg)

**Comment by orwellencarnation** [comment]
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Jan 24 17:49:04 2017 from 172.30.2.100
x@debian:~$ su
Password:
root@debian:/home/x# uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linu                                                                              x
root@debian:/home/x#

**Comment by nikdavnik** [comment]
We have unmet dependencies error in apt, for sogo package.
I think that was coused by new sogo repository. We need to delete it and try again. 
And I need access to your machine to find out the real problem
![sogoerror](https://cloud.githubusercontent.com/assets/17772064/22308806/efb62958-e361-11e6-83b1-280a48c16913.png)

**Comment by orwellencarnation** [comment]
dont tell me you want to acces my machine via github
you have my fcking skype and emai and phone
