### ISSUE TITLE
URGENT APP-installation-script fails unable to install-apt-transport-https

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#196]
GUYS definetively your not testing a shit the commits before in any hardware.
Could you please test the scripts before commiting in github?

**Comment by orwellencarnation** [comment]
I CAN NOT SEE ANY LOG FILE CREATED IN TMP

**Comment by nikdavnik** [comment]
log files are in /var

apt-get-install-aptth.log   
apt-get-update.log	
apt-get-install_1.log	   
apt-get-install_2.log	    
apt-get-update-default.log  
libre_install.log 
libre_config.log
