### ISSUE TITLE
Luis Narvaez Script app-installation-script.sh  fails on configure_repositories function 

### ISSUE THREAD

**Issue by luisnarvaez19** [Librerouter/Librekernel#197]

**Comment by orwellencarnation** [comment]
Please paste the logs

**Comment by luisnarvaez19** [comment]
![unable to set time](https://cloud.githubusercontent.com/assets/25373357/22438078/feeb0752-e700-11e6-8e30-378ceaa7195a.png)
![var-libre-install-log](https://cloud.githubusercontent.com/assets/25373357/22438155/47abb36a-e701-11e6-9ffd-452983e711e3.png)

**Comment by luisnarvaez19** [comment]
Screenshot of app-installation-script.sh

Screenshot of /var/libre_install.log

**Comment by nikdavnik** [comment]
can you do ping to ntp.ubuntu.com

**Comment by orwellencarnation** [comment]
DNS server in unbound should point OPENNIC SERVERS

**Comment by nikdavnik** [comment]
we have 5 ntp servers in configuration to try if some of them is not available

ntp.ubuntu.com
0.ubuntu.pool.ntp.org
1.ubuntu.pool.ntp.org
2.ubuntu.pool.ntp.org
3.ubuntu.pool.ntp.org
 
in my machine its ok.
![timeset](https://cloud.githubusercontent.com/assets/17772064/22440325/6c0e5ae6-e74c-11e6-9e4d-21f66d66d51b.png)

**Comment by luisnarvaez19** [comment]
Ya lo resolví

Lo estoy documentando...



Saludos cordiales;



Luis Narváez
Desarrollador Java Senior



2017-01-30 16:26 GMT-04:00 orwellencarnation <notifications@github.com>:

**Comment by orwellencarnation** [comment]
documenta aqui

**Comment by luisnarvaez19** [comment]
Hola Sres.:


En una instalación nueva el app-installation-script.sh da problemas en la
línea 98 realizando el comando:

ntpdate -s ubuntu.ntp.com

El comando no se ejecuta y continúa por todos los elif hasta que llega al
último que dice:

"Error unable to set time"

Se resolvió haciendo:

1. Se agregó la ilínea para instalar ntp:
    sudo apt-get install -y --force-yes ntp

2. En ntpdate -s ubuntu.ntp.com se sustituyó por:

ntpdate -u ubuntu.ntp.com

Al parecer ntpdate trabaja por el puerto 123 y se obtenía un Connection
refuse.

-u    Direct *ntpdate* to use an unprivileged port for outgoing packets.
This is most useful when behind a firewall that blocks incoming traffic to
privileged ports, and you want to synchronize with hosts beyond the
firewall.

*-s    *Divert logging output from the standard output (default) to the
system *syslog* facility. This is designed primarily for convenience of
*cron* scripts.



Saludos cordiales;



Luis Narváez
Desarrollador Java Senior

2017-01-30 17:00 GMT-04:00 orwellencarnation <notifications@github.com>:

**Comment by mogolo** [comment]
implemente? commited?

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique
+4915202629663

**Comment by luisnarvaez19** [comment]
If I have already committed and the error is gone

**Comment by luisnarvaez19** [comment]
The app-installation-script.sh fails in another line ISSUE 200

**Comment by luisnarvaez19** [comment]
Issue 197 ready. Can be closed
