### ISSUE TITLE
FRANCISCO JIMENEZ AND DAVID Implement DNS checking in installation script

### ISSUE THREAD

**Issue by nikdavnik** [Librerouter/Librekernel#198]
There is a need to check and configure dns servers before doing any package downloading/installation

**Comment by fjmz** [comment]
Hi, currently the DNS server that obtains the system is the one that is delivered to him by DHCP, will happen to set the servers of Opennic. Do we use dnscrypt as well?

**Comment by orwellencarnation** [comment]
There is a need to check that we can reach the best openic servers that support cryptdns

**Comment by fjmz** [comment]
Dnscrypt has been implemented, the only problem I have detected is that it is not natively included in systemd. Do I get to work on it?

**Comment by fjmz** [comment]
The dnscrypt service connects to the opennic anycast server, fvz-anyone (ip at this moment: 185.121.177.177) which assigns a server randomly.

**Comment by orwellencarnation** [comment]
evidence of flow with captures

**Comment by orwellencarnation** [comment]
make a diagram of how it works regarding the dns schema in readme

**Comment by orwellencarnation** [comment]
did or not! if so make changes in readme of the dns diagram

**Comment by fjmz** [comment]
I think the function of DNSCrypt is already indicated. In the DNS section. Do you think we should add something else?

The last update is for use same commad for check dns at two scripts (installation and configuration)
