### ISSUE TITLE
wget -O - http://bit.ly/2gbKstn | bash FAIL!!!!!!!!!!!!

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#201]
![e](https://cloud.githubusercontent.com/assets/13025157/22526669/6b8fbad4-e8cc-11e6-9683-f0a0bb69f6f9.jpg)

**Comment by nikdavnik** [comment]
Thats github certificate problem, which is not actual in my machine.
You can try with --no-check-certificate option

wget **--no-check-certificate** -O - http://bit.ly/2gbKstn | bash

**Comment by orwellencarnation** [comment]
why in your machine do not happen?

**Comment by fjmz** [comment]
I am seeing the certificate, it was issued in 2016, but it is possible that when you were downloading, it will not work properly (Re-sign or some change), on my computer right now it works without problem.

I think what you can close this issue.

**Comment by orwellencarnation** [comment]
In resume: Don't fucking idea why this is happening

**Comment by fjmz** [comment]
Yes, that's right, it's really the fault in any case would be the github.

**Comment by orwellencarnation** [comment]
Then is better you continue with other issue
