### ISSUE TITLE
Luis Narvaez Error: Unable to start unbound DNS server.  I attach the log files

### ISSUE THREAD

**Issue by luisnarvaez19** [Librerouter/Librekernel#203]

**Comment by luisnarvaez19** [comment]
![issue 203 log libre_config](https://cloud.githubusercontent.com/assets/25373357/22695304/b3550c54-ed20-11e6-825a-2de3d69335f7.png)
![issue 203 error unbound dns](https://cloud.githubusercontent.com/assets/25373357/22695310/b5f241fc-ed20-11e6-8a12-94a0d29154a9.png)

**Comment by luisnarvaez19** [comment]
I already notify David of this issue

**Comment by luisnarvaez19** [comment]
![journalctl -xn](https://cloud.githubusercontent.com/assets/25373357/22695588/a2f7418c-ed21-11e6-9549-59b9ce84729b.png)

**Comment by luisnarvaez19** [comment]
The first log:  app-configuration-script.sh print screen
second log:  file /var/libre_config.log
third log:  journalctl -xn

**Comment by luisnarvaez19** [comment]
This error is happening when I run the app-configuration-script.sh.  After issue 202 was resolved with the same script

**Comment by fjmz** [comment]
The only thing that was done in the 202 has been add the file (create it empty) so that after the stuffed sea, I doubt much that the sea blames that.

A greeting.

**Comment by luisnarvaez19** [comment]
Hi Francisco: If the important thing is that it runs automatically without errors. We know that users do not have to create files or make no matter how easy it is.

**Comment by fjmz** [comment]
I'm testing on a fresh install, the only thing I wanted to say is that the error is not related to the 202, which simply lacked a file.
Are you using a clean installation? I am with a issue related to unbound and dnscrypt, I will solve it.
At the moment I only have it in the testing laboratory, in a few hours it will be uploaded, therefore, I will try to reproduce your problem.

**Comment by fjmz** [comment]
The 'fix' of #202 https://github.com/Librerouter/Librekernel/commit/d7b40cf943d49ad4e1f81eac5ff376c33221c60b

**Comment by luisnarvaez19** [comment]
I think you explain me wrong. I wrote issue 202 resolved

**Comment by luisnarvaez19** [comment]
Issue 203 The only match with issue 202 is that both occur when you run the script app-configuration-script.sh. But I repeat, issue 202 is resolved. That mistake did not happen to me again.

**Comment by orwellencarnation** [comment]
your not installing via ssh right?

**Comment by luisnarvaez19** [comment]
Of course not. I am configuring directly from the computer.


Saludos cordiales;



Luis Narváez
Senior Java Developer


2017-02-07 13:14 GMT-04:00 orwellencarnation <notifications@github.com>:

**Comment by fjmz** [comment]
To me from a clean installation and from the console (SIN SSH) works me correctly, I just implemented DNSCrypt with Opennic.

Other can reproduce this problem?

**Comment by orwellencarnation** [comment]
you implemented unbound with dnscrypt and opennic?

**Comment by nikdavnik** [comment]
with teamwiever session I and Lius tested unbound issue.
The problem was with Lius's virtual machine which has no ethernet interfaces connected.

In my physical machine with 2 eths there is no onbound problem.

Luis, unbnound server needs network interface with ip 10.0.0.1 to start. Please connect network interfaces to your physical machine and test again. I am sure unbount will start smoothly,

**Comment by luisnarvaez19** [comment]
It is ready. I fix the network interfaces on my machines and The script run perfectly.

The issue can be closed.

**Comment by orwellencarnation** [comment]
next time  RTFM and dont input waste hours for nothing
