### ISSUE TITLE
Eliminate all > /dev/null in all scripts and make fucking LOG! IN ALL FUCKING SCRITPS

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#204]

**Comment by nikdavnik** [comment]
Moved all outputs from /dev/null into log files.
For installation and configuration scripts

**Comment by JFrancoJ** [comment]
Hi, this is related with setup.sh I did to report all logs to the librereport @ github
Don't need to move to log files, as this is already done on setup.sh and auto commit to librereport 
setup.sh includes the redirections for stdio and stderr 

I have not full tested my setup.sh on new installation due Debian 8.7.1 repositories issue, but once fixed I am going to commit automatically the outputs to librereport

**Comment by nikdavnik** [comment]
Fronco please test your git setup script.
it fails in my machine
#209
