### ISSUE TITLE
DAVID app-configuration: move install of bridge-utilities to app-installation

### ISSUE THREAD

**Issue by m4tu5** [Librerouter/Librekernel#205]
https://github.com/Librerouter/Librekernel/blob/gh-pages/app-configuration-script.sh#L319

package installation should ocurr in app-installation-script

the existance of this function here negativelly impacts #195

**Comment by orwellencarnation** [comment]
Well done ,,,,,DAVID!!!!!!!  bad ass is David. He guaranteed me all installation occured in instalation script....
WTF!

**Comment by nikdavnik** [comment]
this is commented and NOOOOOOOOOOOOOOOOT USEEEEEEEEEEDDDDDDDDD

**Comment by orwellencarnation** [comment]
DELETE IT FROM CONFIGURATION!

**Comment by nikdavnik** [comment]
Deleted. can be closed.
