### ISSUE TITLE
Franciso jimenez Implement dns checking resolve in both script and replace the poor ping to 8.8.8.8

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#207]
Connectivity and dns resolution is a requirement of both scripts

**Comment by fjmz** [comment]
Today will be done part of the other script too. (need add the code to app-configuration-script)

**Comment by orwellencarnation** [comment]
did or not!

**Comment by nikdavnik** [comment]
Dns checking implemented. This can be closed
