### ISSUE TITLE
apt-get  fails on Debian 8.7.1-amd64

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#208]
root@debian:~# apt-get -y --force-yes install ntp ntpdate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntp : Depends: libopts25 (>= 1:5.18.4) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by nikdavnik** [comment]
again no problems in my machine

![test](https://cloud.githubusercontent.com/assets/17772064/22836128/9a94e822-efd4-11e6-97d5-ee464a1886a9.png)

**Comment by nikdavnik** [comment]
![test2](https://cloud.githubusercontent.com/assets/17772064/22836324/5c821b30-efd5-11e6-8013-1ceeda129c05.png)

**Comment by nikdavnik** [comment]
It seems it has an issue because you are installing it into a VM.
Are you using virtualbox?

**Comment by JFrancoJ** [comment]
No David, I am installing it on a qotom, nothing related with VM
I guess may be success with local CD/DVD but not if repositories are 
from the internet.
Did you installed any repo from CD/DVD and then go to the internet ? O 
did you just did clear installation
and take everything from internet debi repos ?



root@debian:~# apt-get -y --force-yes install ntp ntpdate
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  ntp : Depends: libopts25 (>= 1:5.18.4) but it is not installable
E: Unable to correct problems, you have held broken packages.


David wrote:

**Comment by nikdavnik** [comment]
nothing from CD/DVD, 
everything from repositories we have in app-installation-script.

**Comment by JFrancoJ** [comment]
did you commented out this in /etc/apt/souces.list file

deb cdrom:[Debian GNU/Linux 8.7.1 _Jessie_ - Official amd64 DVD Binary-1 
20170116-11:01]/ jessie contrib main

to come sure nothing, even before to run app-installation-script.sh 
comes from the local repository on the dvd ?

Please can you give your /etc/apt/sources.list file ?
Thanks



David wrote:

**Comment by nikdavnik** [comment]
I am installing  "debian-8.7.1-amd64-netinst"  (with no gui, no ssh/print server,  no utils).
then I am downloading and running scripts. (I do not do anything manually, nothing in nowhere, just running scripts.)

here is my source list after scripts installation.

![source](https://cloud.githubusercontent.com/assets/17772064/22837613/cd2c7b3c-efda-11e6-8f7a-ffed7b28d24c.png)

**Comment by JFrancoJ** [comment]
ok, seems may be related with locals or something like that , my sources.list was not ok.
I added:
deb http://ftp.debian.org/debian jessie main contrib non-free
deb http://ftp.debian.org/debian jessie-updates main contrib non-free
deb http://security.debian.org jessie/updates main coentrib non-free
deb http://ftp.debian.org/debian jessie-backports main contrib non-free
deb-src http://ftp.debian.org/debian jessie main contrib non-free
deb-src http://ftp.debian.org/debian jessie-updates main contrib non-free
deb-src http://security.debian.org jessie/updates main contrib non-free
deb-src http://ftp.debian.org/debian jessie-backports main contrib non-free

and seems worked.
I would recomend if someone faced similar issue with installation to place these in the sources.list

**Comment by JFrancoJ** [comment]
Hi David,
sorry, my mistake
the error was due lack of git-init
Please add:

chmod 700 ssh_key
*git init*
git config --global user.email "kinko@interec.og"
git config --global user.name "Reporter"
eval $(ssh-agent -s)
ssh-add /root/librereport/ssh_key

That must create /root/librerport/.git with several files and 
directories inside
required to see the directory as a local repository git

**Comment by nikdavnik** [comment]
Franco, Please sent me fully tested and working setup.sh file.

**Comment by orwellencarnation** [comment]
non free , NO!

**Comment by orwellencarnation** [comment]
David I told you in skype about possible solutions why you dont upgrade the issue with those?
