### ISSUE TITLE
URGENT DAVID IMPLEMENT AND FIX IT! git setup.sh fails

### ISSUE THREAD

**Issue by nikdavnik** [Librerouter/Librekernel#209]
![setup_git](https://cloud.githubusercontent.com/assets/17772064/22836738/0d5c55fa-efd7-11e6-9f4a-f1260a398bfc.png)

**Comment by nikdavnik** [comment]
setup.sh implemeted.
It pushes log files into github.com/librerouter/librereports

**Comment by orwellencarnation** [comment]
FRANCO ANY UPDATE!
