### ISSUE TITLE
VERY URGENT i2P configuration script

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#215]
![kokokok](https://cloud.githubusercontent.com/assets/13025157/22864093/10a016a0-f14b-11e6-9e7a-a1f22192e744.jpg)

**Comment by fjmz** [comment]
I made a modification to avoid the problem of the lost file, David removed it from the code, said that it was not necessary according to him, I do not know if that worked correctly but less let the configuration continue and finish script, I do now in my local installation.

**Comment by nikdavnik** [comment]
fixed. Someone please test and confirm
