### ISSUE TITLE
round cube need to be in tor and all the others hidden services need to be tested from TOR

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#220]
![roundubetor](https://cloud.githubusercontent.com/assets/13025157/22864771/9b15530c-f157-11e6-8caf-2b89b5c4b0d1.jpg)

**Comment by orwellencarnation** [comment]
only roundcube is missing in TOR

**Comment by nikdavnik** [comment]
added 
![round6](https://cloud.githubusercontent.com/assets/17772064/22896489/c58d5ae8-f239-11e6-9bd2-865a0e476444.png)
