### ISSUE TITLE
Librerouter DNS service

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#224]
nslookup ixxxxxxxxxxxxxxxxxxxxx.onion
;; connection timed out; no servers could be reached

 nmap 10.0.0.1 -p 53

Starting Nmap 6.40 ( http://nmap.org ) at 2017-02-15 20:54 GMT
Nmap scan report for 10.0.0.1
Host is up (0.00038s latency).
PORT   STATE  SERVICE
53/tcp closed domain
MAC Address: 00:30:48:58:C8:99 (Supermicro Computer)

19:59:08.397703 IP 10.0.0.101 > 10.0.0.2: ICMP 10.0.0.1 udp port 53 unreachable, length 69

**Comment by fjmz** [comment]
It happens to you also with domains that are not from the network tor I suppose. Could you attach the errors you get from unbound? I'm going to do some tests in a little while.

**Comment by JFrancoJ** [comment]
yeah, any domain.
I also tried :

tor-resolve -v -5 oysh6edjf2dwrrxi.onion
Feb 15 21:47:01.864 [debug] main(): defaulting to localhost
Feb 15 21:47:01.864 [debug] main(): defaulting to port 9050
Feb 15 21:47:01.864 [warn] Got SOCKS5 status response '4': host is 
unreachable
Feb 15 21:47:01.864 [warn] oysh6edjf2dwrrxi.onion is a hidden service; 
those don't have IP addresses. You can use the AutomapHostsOnResolve 
option to have Tor return a fake address for hidden services.  Or you 
can have your application send the address to Tor directly; we recommend 
an application that uses SOCKS 5 with hostnames.

where oysh6edjf2dwrrxi.onion is up and connected ( one of my tahoe nodes ).

curl --socks5 127.0.0.1:9050 xxxxxxxxxxxxxxx.onion
curl: (6) Could not resolve host: xxxxxxxxxxxxxxx.onion



fjmz wrote:

**Comment by orwellencarnation** [comment]
Do nslookup and show me the dns server by default


---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique
+4915202629663

**Comment by mogolo** [comment]
show nslookup server you got via dhcp not manual!

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique
+4915202629663

**Comment by mogolo** [comment]
nslookup ENTER

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique
+4915202629663

**Comment by JFrancoJ** [comment]
/Client side:/
root@venus:~\ nslookup google.es 10.0.0.1
;; connection timed out; no servers could be reached

root@venus:~\ nslookup oysh6edjf2dwrrxi.onion 10.0.0.1
;; connection timed out; no servers could be reached


/Librerouter side:/

09:29:27.690011 IP 10.0.0.101.46152 > 10.0.0.1.53: 40803+ A? 
oysh6edjf2dwrrxi.onion. (40)
09:29:27.690058 IP 10.0.0.1 > 10.0.0.101: ICMP 10.0.0.1 udp port 53 
unreachable, length 76

root@librerouter:~# nslookup google.es 10.0.0.1
;; connection timed out; no servers could be reached

root@librerouter:~# tor-resolve google.es
216.58.212.195

tor-resolve oysh6edjf2dwrrxi.onion
Feb 16 09:33:12.157 [warn] Got SOCKS5 status response '4': host is 
unreachable
Feb 16 09:33:12.157 [warn] oysh6edjf2dwrrxi.onion is a hidden service; 
those don't have IP addresses. You can use the AutomapHostsOnResolve 
option to have Tor return a fake address for hidden services.  Or you 
can have your application send the address to Tor directly; we recommend 
an application that uses SOCKS 5 with hostnames.






orwellencarnation wrote:

**Comment by mogolo** [comment]
Kiyo

nslkoop _>>>enter

---
Thanks in advance.
Gracias de antemano.
Vielen Dank.
Best Regards.
Un saludo cordial.
Mit Gruesse.
Enrique
+4915202629663

**Comment by JFrancoJ** [comment]
client side:

Eth0 IP ( from dhcp ) 10.0.0.100 255.255.255.0

/etc/resolv.conf ( from dhcp )

search librerouter.librenet
nameserver 10.0.0.1

  nslookup
 > google.es
;; connection timed out; no servers could be reached
 >




mogolo wrote:

**Comment by JFrancoJ** [comment]
;;connection timeout; no servers could be reached

tcpdump on librerouter:

09:29:27.690011 IP 10.0.0.101.46152 > 10.0.0.1.53: 40803+ A? 
oysh6edjf2dwrrxi.onion. (40)
09:29:27.690058 IP 10.0.0.1 > 10.0.0.101: ICMP 10.0.0.1 udp port 53 
unreachable, length 76

Tor is fine for tahoe nodes running in same box , no problems.


mogolo wrote:
> Kiyo
>
> nslkoop _>>>enter
>
> ---
> Thanks in advance.
> Gracias de antemano.
> Vielen Dank.
> Best Regards.
> Un saludo cordial.
> Mit Gruesse.
> Enrique
> +4915202629663
>
> El 2017-02-16 09:34 AM, JFrancoJ escribió:
> > /Client side:/
> > root@venus:~\ nslookup google.es 10.0.0.1
> > ;; connection timed out; no servers could be reached
> >
> > root@venus:~\ nslookup oysh6edjf2dwrrxi.onion 10.0.0.1
> > ;; connection timed out; no servers could be reached
> >
> > /Librerouter side:/
> >
> > 09:29:27.690011 IP 10.0.0.101.46152 > 10.0.0.1.53: 40803+ A?
> > oysh6edjf2dwrrxi.onion. (40)
> > 09:29:27.690058 IP 10.0.0.1 > 10.0.0.101: ICMP 10.0.0.1 udp port 53
> > unreachable, length 76
> >
