### ISSUE TITLE
Apache2 does not work.

### ISSUE THREAD

**Issue by fjmz** [Librerouter/Librekernel#227]
With a fresh install, after i reviewing the logs.. i found this bug:

Apache2 not start, this problem its with virtual host of sogo.

feb 21 20:21:01 librerouter apache2[1208]: The apache2 configtest failed. ... (warning).
feb 21 20:21:01 librerouter apache2[1208]: Output of config test was:
feb 21 20:21:01 librerouter apache2[1208]: AH00526: Syntax error on line 47 of /etc/apache2/conf-enabled/SOGo.conf:
feb 21 20:21:01 librerouter apache2[1208]: Invalid command 'ProxyRequests', perhaps misspelled or defined by a module not included in the server configuration
feb 21 20:21:01 librerouter apache2[1208]: Action 'configtest' failed.

**Comment by nikdavnik** [comment]
the configuration file sogo.conf was cousing this problem. 
This file is default apache configuration file and have been installed with sogo package installation.
As we are running sogo in nginx, we do not need sogo configuration for apache.

I removed sogo apache configuration.  Issue fixed.
