### ISSUE TITLE
Check all network status in /root/libre_scripts/check_interfaces.sh

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#231]
Must check internet connection too, pinging 8.8.8.8 or checking any other services ( curl for google:80 , tahoe nodes statuses, lack of any traffic in interface, etc)
In the event internet is lost must redirect all HTTP and HTTPS requests to a local web page informing the issue and asking user to check his/her internet connection, all MTA that must reach external servers must also return 550 Error connecting to end server, and so on.
As soon as internet connection comes up again and ready, must check all external sockets and services still alive and have been not disconnected. 
Some services may require to be restarted if they was stoped by disconnection ( i.e. backup )

**Comment by nikdavnik** [comment]
I put script into if-up.d and if-post-down.d directories, So now it will run if interface goes down or comes up

**Comment by JFrancoJ** [comment]
ok. I will close this issue
