### ISSUE TITLE
app-configuration-script.sh lack of shallalist.tar.gz causes exit 6

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#232]
On app-configuration-script.sh line 1961 the script exits with errlevel 6 if shallalist.tar.gz is missed.
Must continue and don't abort due failure on this step (?)

**Comment by nikdavnik** [comment]
this can happen if you 
1. havn't run app-installation-script before running configuration script
2. if you run app-configuration-script in other directory that configuration script.

I added fix for 2nd case.

**Comment by JFrancoJ** [comment]
Hi david

I have modified tahoe2() function in a way now new_install.sh is 
creatign a separate script
that must be called on the next first reboot or from wizard.sh

I got several errors on configuration script, you are right I did not 
re-run the installation script
this time .

May be some non critical errors on configuration script must not break 
and abort the full configuration.
Will close issue #232





David wrote:
