### ISSUE TITLE
(URGENT) Problem with app-installation-script.sh

### ISSUE THREAD

**Issue by jkdc** [Librerouter/Librekernel#233]
Hi everybody! I have a problem when run app-installation-script.sh. In this image you can see wich ask me if I want to install a package. I run the script in debian installation and it must be unattended. Someone know why happend this problem? I think it happens in install_tahoe().
![fail](https://cloud.githubusercontent.com/assets/12255305/23319837/8c1ee572-fad8-11e6-8beb-bda7d1095ef9.jpg)

**Comment by nikdavnik** [comment]
Fixed. I added -y --force-yes options to skip question
