### ISSUE TITLE
DAVID:  Suricata for TOR traffic

### ISSUE THREAD

**Issue by nikdavnik** [Librerouter/Librekernel#236]
There is a need to implement suricata for TOR traffic

**Comment by orwellencarnation** [comment]
Document here the recopilation of info for the email and copy here the email you NEED TO SEND ASAP

**Comment by libreroot** [comment]
I got suricata catching tor traffic. Here is suricata's json log where you can see traffic to destination port 3129 which is squid proxy port for tor.
![suricata](https://cloud.githubusercontent.com/assets/26331324/23919811/c55fb82e-0911-11e7-88c7-ae9398f7fd15.png)

**Comment by orwellencarnation** [comment]
show me the suricata GUI

**Comment by libreroot** [comment]
I am working on kibana configuration. I enbled it in script. It is working, I will connect it to suricata soon
![kibana](https://cloud.githubusercontent.com/assets/26331324/23923324/a221512a-091f-11e7-9c57-bdee8d998025.png)

**Comment by orwellencarnation** [comment]
I dont see Suricata logs
