### ISSUE TITLE
app-configuration-script.sh Job for unbound.service failed. 

### ISSUE THREAD

**Issue by mariacrangel** [Librerouter/Librekernel#238]
When I ran app-configuration-script.sh this is an error out 

> i2p successfully configured
> Configuring unbound DNS server ...
> Extracting files ...
> Configuring domain list ...
> Stoping dnsmasq ...
> app-configuration-script.sh: line 2047: kill: (20924) - No such process
> Starting Unbound DNS server ...
> Job for unbound.service failed. See 'systemctl status unbound.service' and 'journalctl -xn' for details.
> Error: Unable to start unbound DNS server. Exiting

Then I did systemctl status unbound.service

> ● unbound.service - (null)
>    Loaded: loaded (/etc/init.d/unbound)
>   Drop-In: /run/systemd/generator/unbound.service.d
>            └─50-insserv.conf-$named.conf, 50-unbound-$named.conf
>    Active: failed (Result: resources) since Wed 2017-03-01 04:57:44 EST; 12min ago
>   Process: 20934 ExecStart=/etc/init.d/unbound start (code=exited, status=0/SUCCESS)
> 
> Mar 01 04:57:44 librerouter unbound-anchor[20941]: /var/lib/unbound/root.key has content
> Mar 01 04:57:44 librerouter unbound-anchor[20941]: success: the anchor is ok
> Mar 01 04:57:44 librerouter unbound[20934]: Starting recursive DNS server: unbound[1488362264] unbound[20943:0] error: can't bind socket: Address already in use
> Mar 01 04:57:44 librerouter unbound[20934]: [1488362264] unbound[20943:0] debug: failed address 10.0.0.1 port 53
> Mar 01 04:57:44 librerouter unbound[20934]: [1488362264] unbound[20943:0] fatal error: could not open ports
> Mar 01 04:57:44 librerouter unbound[20934]: failed!
> Mar 01 04:57:44 librerouter systemd[1]: PID file /run/unbound.pid not readable (yet?) after start.
> Mar 01 04:57:44 librerouter systemd[1]: Failed to start (null).
> Mar 01 04:57:44 librerouter systemd[1]: Unit unbound.service entered failed state.

then nmap out:

>  nmap localhost
> 
> Starting Nmap 6.47 ( http://nmap.org ) at 2017-03-01 05:11 EST
> Nmap scan report for localhost (127.0.0.1)
> Host is up (0.000030s latency).
> rDNS record for 127.0.0.1: localhost.librenet
> Not shown: 978 closed ports
> PORT      STATE SERVICE
> 22/tcp    open  ssh
> 25/tcp    open  smtp
> 53/tcp    open  domain
> 80/tcp    open  http
> 143/tcp   open  imap
> 465/tcp   open  smtps
> 587/tcp   open  submission
> 3000/tcp  open  ppp
> 3306/tcp  open  mysql
> 4444/tcp  open  krb524
> 4445/tcp  open  upnotifyp
> 5222/tcp  open  xmpp-client
> 5269/tcp  open  xmpp-server
> 6668/tcp  open  irc
> 8000/tcp  open  http-alt
> 8080/tcp  open  http-proxy
> 8090/tcp  open  unknown
> 8888/tcp  open  sun-answerbook
> 9000/tcp  open  cslistener
> 9050/tcp  open  tor-socks
> 10024/tcp open  unknown
> 20000/tcp open  dnp
>

**Comment by nikdavnik** [comment]
Please post here output of "ifconfig" command

**Comment by mariacrangel** [comment]
eth0      Link encap:Ethernet  HWaddr 08:00:27:51:4a:eb  
          inet addr:192.168.1.109  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3536720 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1573596 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2523350413 (2.3 GiB)  TX bytes:514585966 (490.7 MiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.1  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:525 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4680 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:53394 (52.1 KiB)  TX bytes:652225 (636.9 KiB)

eth1:1    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.251  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:2    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.252  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:3    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.253  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:4    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.254  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:5    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.245  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:6    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.250  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:7    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.239  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:8    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.12  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:9    Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.246  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:10   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.247  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:11   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.248  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:12   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.249  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:13   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.244  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:14   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.243  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:15   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.242  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:16   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.241  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:17   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.240  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:18   Link encap:Ethernet  HWaddr 08:00:27:ef:87:66  
          inet addr:10.0.0.238  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2224053 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2224053 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:171816460 (163.8 MiB)  TX bytes:171816460 (163.8 MiB)

**Comment by nikdavnik** [comment]
please also post output of

netstat -tulpn | grep :53

and 

service unbound restart

**Comment by mariacrangel** [comment]
# netstat -tulpn | grep :53
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      26296/dnsmasq   
tcp6       0      0 :::53                   :::*                    LISTEN      26296/dnsmasq   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           21361/chrome    
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1831/avahi-daemon: 
udp        0      0 0.0.0.0:53              0.0.0.0:*                           26296/dnsmasq   
udp6       0      0 :::5353                 :::*                                1831/avahi-daemon: 
udp6       0      0 :::53                   :::*                                26296/dnsmasq 

# service unbound restart
Job for unbound.service failed. See 'systemctl status unbound.service' and 'journalctl -xn' for details.

# systemctl status unbound.service
● unbound.service - (null)
   Loaded: loaded (/etc/init.d/unbound)
  Drop-In: /run/systemd/generator/unbound.service.d
           └─50-insserv.conf-$named.conf, 50-unbound-$named.conf
   Active: failed (Result: resources) since Wed 2017-03-01 05:29:40 EST; 52s ago
  Process: 22800 ExecStart=/etc/init.d/unbound start (code=exited, status=0/SUCCESS)

Mar 01 05:29:40 librerouter unbound-anchor[22807]: /var/lib/unbound/root.key has content
Mar 01 05:29:40 librerouter unbound-anchor[22807]: success: the anchor is ok
Mar 01 05:29:40 librerouter unbound[22800]: Starting recursive DNS server: unbound[1488364180] unbound[22809:0] erro...ddress
Mar 01 05:29:40 librerouter unbound[22800]: [1488364180] unbound[22809:0] debug: failed address 10.0.0.1 port 53
Mar 01 05:29:40 librerouter unbound[22800]: [1488364180] unbound[22809:0] fatal error: could not open ports
Mar 01 05:29:40 librerouter unbound[22800]: failed!
Mar 01 05:29:40 librerouter systemd[1]: PID file /run/unbound.pid not readable (yet?) after start.
Mar 01 05:29:40 librerouter systemd[1]: Failed to start (null).
Mar 01 05:29:40 librerouter systemd[1]: Unit unbound.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by nikdavnik** [comment]
ok, thanks, Please also do these

ps aux | grep dnsmasq 

and

ps aux | grep dnsmasq | awk {'print $2'} | sed -n '1p'

**Comment by mariacrangel** [comment]
# ps aux | grep dnsmasq
root     22882  0.0  0.0  12728  2188 pts/2    S+   05:31   0:00 grep dnsmasq
dnsmasq  26296  0.0  0.0  36744  2428 ?        S    Feb28   0:00 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

# ps aux | grep dnsmasq | awk {'print $2'} | sed -n '1p'
22890

**Comment by nikdavnik** [comment]
Please do

cat /etc/issue

and

uname -a

**Comment by mariacrangel** [comment]
# cat /etc/issue
Debian GNU/Linux 8 \n \l

#uname -a
Linux librerouter 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Comment by nikdavnik** [comment]
somehow you have dnsmask installed in yout machine, which is not allowing unbound to start
In my fresh debian machine, there is no dnsmask installed by default.

Maria, have you installed dnsmask in your machine, or any additional packages? (I mean package which do not exist in our scripts)

and how you installed your debian, in ordianty way? or you use something else this time?

**Comment by mariacrangel** [comment]
I am installing librerouter over my old installation of librerouter, I re run app-installation-script.sh, then installed some packages and then I ran app-configuration-script.sh, Then you say that, might I  install in a fresh machine?

**Comment by nikdavnik** [comment]
Can you install on fresh machine? if yes please do and let me know the result

**Comment by mariacrangel** [comment]
ok, I will do it.

**Comment by nikdavnik** [comment]
Ok, I also added fix, if there si dnsmask running in router.
Thank you.

**Comment by mariacrangel** [comment]
I installed librerouter in a fresh machine and all configuration works with this new installation.
