### ISSUE TITLE
Joakin Circuitos : Network interfaces auto detection

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#240]
The goal is avoid user to need to configure network interfaces.
Two stages must be taken into consideration:

a) The hardware is completed and has enough NICs ( ethernets or WIFI)
b) The hardware or wired have been changed by the user i.e. if the box is moved to another room where change from wired to wifi is required.

Once detected network hardware several cases and scenarios will be show.
Case 1. No any network card. Let's prepare for stage b)
Case 2. Just one network interface, Eth or WIFI. 
Case 3. Two Eth interfaces
Case 4. One Eth and one WiFi interfaces
Case 5. Two WiFi interfaces
Case 6  More than 2 interfaces

For cases 3 to 6, we will need to detect what interface is used for wan ( internet access ) and what one is used for lan ( private secure internal network )

Detect what interface is the wan one may be not hard, but detect what interface ( if more than 2 ) is going to be use for lan , if the user has not yet connected any host and can be discover by dhcp , may be an issue.

**Comment by orwellencarnation** [comment]
Joakin Circuitos please check both app-installation and configuration script to complement in the wizard and repair those scripts according bridge if it is not there
So please paste here first part of the analysis. of both scripts.

**Comment by orwellencarnation** [comment]
What its th eouput of this?

**Comment by JFrancoJ** [comment]
Added in wizard.sh network detection/configuration
