### ISSUE TITLE
CRITICAL apt upgrade repository errors

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#246]
Critical
Failed repository upgrade cause app-installation-scoript.sh comes incompleted and cause several issues like not resolving.

Detected on deb.i2p2.no where now is listening only on HTTPS, but claims about certificate in the local box that is issued for *.i2p2.de .
Changing to https://deb.i2p2.de seems working fine now.

Other reposotories still failing, ie:

W: Failed to fetch http://download.webmin.com/download/repository/dists/sarge/Release.gpg  Connection failed

W: Failed to fetch https://dl.dropboxusercontent.com/u/18621288/debian/dists/wheezy/main/binary-amd64/Packages  HttpError404

**Comment by orwellencarnation** [comment]
# Prepare tahoe repo
		echo 'deb https://dl.dropboxusercontent.com/u/18621288/debian wheezy main' > /etc/apt/sources.list.d/tahoei2p.list
		apt-key advanced --keyserver pgp.net.nz --recv-keys 8CF6E896B3C01B09

**Comment by orwellencarnation** [comment]
which line of the script is https://dl.dropboxusercontent.com/u/18621288/debian/dists/wheezy/main/binary-amd64/Packages   ?

**Comment by JFrancoJ** [comment]
tahoei2p.list is not longer required. Tahoe is installing witouth this repo. 
I am going to remove tahoei2p.list locally and testing.
Once passed I will comit a new app-installation-script.sh

**Comment by orwellencarnation** [comment]
ok

**Comment by JFrancoJ** [comment]
There a big issue, due if one of multiple packet to install failed, then next packet is NOT installed,, i.e. libsystem-dev is not installing, then dnscrypt-proxy fails to configure&make, then unbound is not able to resolv external sites, but the scripts overwrote the /etc/resolv.conf and force to use only the local unbound service, that of course fails to resolv any further task due not resolv.

**Comment by orwellencarnation** [comment]
Please open issues for:
a) dnscrypt problem
b) separate and segregate apt-get s all need to have maximun debug possible in same log file.
c) how to bypass error in url changes of things that we download from urls.
d) any other thing commented today
