### ISSUE TITLE
Joakin circuitos Apt volatile repositories and Github sources revisions

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#249]
Volatile includes also those that did some updates and actual versions cause conflict on Librerouter.
Others are just refusing connection.
Is required to do a policy adding repositories and filter out those that are not ok, replacing with the
right one if available.
This policy must check no just the packet is available, also any changes in dependencies.
If doubt then better from sources from good enough sites.
Also all actual already downloaded from github sites must be under revision, due the administrator can remove it at any time, or change it and cause Librerouter fails.

**Comment by orwellencarnation** [comment]
I dont see the next steps here or the output of this issue

**Comment by JFrancoJ** [comment]
Moved to issue #258
