### ISSUE TITLE
URGENT JOAKIN FRANCO :  From the WAN ICMP protocol need to be allowed for internet connection test purposes.

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#263]
This is the 3rd time.

**Comment by orwellencarnation** [comment]
This is fixed Joaking?

**Comment by JFrancoJ** [comment]
fixed days ago 
Worked for me on my two computers.
The iptables rule is just one now, very simple and not hardcored to interface name.

**Comment by orwellencarnation** [comment]
commited?

**Comment by JFrancoJ** [comment]
orwellencarnation wrote:
>
> commited?
>
Yes. Except exceptions when I say "fixed" implies commited.
