### ISSUE TITLE
David urgent Qotom never finish to shutdown as happened in the past with other devices. issue again come back

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#264]
![eee](https://cloud.githubusercontent.com/assets/13025157/24568987/6e6ec5c2-1664-11e7-890a-df12d34f9eaf.jpg)

**Comment by orwellencarnation** [comment]
http://unix.stackexchange.com/questions/186162/how-to-change-timeout-in-systemctl

**Comment by orwellencarnation** [comment]
/etc/systemd/system.conf

#DefaultTimeoutStartSec=90s
#DefaultTimeoutStopSec=90s

This should change globally.

    enlaceembedpadre

[–][deleted] 1 punto hace 1 año 

Thank you. I assume that could still be overridden by other units, but the fact that I was seeing a 90 second timeout gives me hope that this default will change it.

    enlaceembedpadre

[–]jampola 3 puntos hace 1 año* 

Yep. For example, run:

$ systemctl show sshd -p TimeoutStopUSec

Will spit pit the TimeoutStopUSec value, on my machine, it prints:

TimeoutStopUSec=1min 30s

Now, say you wish to change it to 30s opposed to 90s (1min 30s), open up the sshd.service file (mine is in /etc/systemd/system) and under "[Service]", you can add:

TimeoutStopUSec=30s

**Comment by JFrancoJ** [comment]
Fixed.
This fix also avoid some errors on boot when the last power-off was forced

The 3 proceess called from /etc/rc.local moved to the background.
# Start Redmine
thin -c /opt/redmine/redmine-3.3.1 --servers 1 -e production -a 127.0.0.1 -p 8889 -d start > /dev/null 2>&1 &

# Start Redsocks
/opt/redsocks/redsocks -c /opt/redsocks/redsocks.conf &
...

echo '/bin/bash /usr/bin/dnscrypt-proxy.sh &
exit 0' >> /etc/rc.local
