### ISSUE TITLE
DAVID JOAKINFRANCO The multiple cron and scripts for checking WAN and LAN connectivity Watchdog

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#265]
None of the work and much hours you spent in making LAN and WAN to be up and having IP is working.
At least not in the WAN.
If somebody disconnect the cable in WAN never take IP again.

**Comment by JFrancoJ** [comment]
Due dhclient is killed after got IP/routing/dns 
This may be fixed if after reboot one instance of dhcclient still alive.
Notice dhclient may be killed and restarted from wizard.sh, so also wizard.sh will need to leave one dhclient alive.

**Comment by orwellencarnation** [comment]
No, there need to be cron that check if there is IP in the WAN and try the latest config done in wizard reseting the WAN down up.
If was fixed then need to be using fixed 
If was dhcp then the cron need to check if there is any ip in the wan if not try again dhclient. If the cron daemon is checking and there is IP in the WAN then nothing need to be changed.
BUT THIS NEED TO BE IMPLEMENTED ASAP

**Comment by JFrancoJ** [comment]
Daemonized chclient have been added in wizard. This will avoid interface lose the default gw/ip in the event the cable connection or wifi connection comes lost

**Comment by orwellencarnation** [comment]
Which test did you did?

**Comment by JFrancoJ** [comment]
start dhclient ethX ( nothing new happens )
ping/resolv still ok.
disconnect eth wire and wait few minutes.
confirms ping and resolving was not ok now.
re-connect wire and check if the service have been restored.

Leaving live dhclient causes if interface comes down, the librerouter 
will send dhcp requests on up again
and the connection comes back.

This NOT check the LAN, just the wan interface. If LAN face some 
physical ( or WIFI ) issue leaving dhclient
will not fix, but LAN already have all time a running dhcpd as server to 
offer ip/dns/gw to the hosts on the
lan, so if some host in lan is temporary disconnected, is expected this 
host will retry dhcp query to 10.0.0.1
and recover


orwellencarnation wrote:
