### ISSUE TITLE
Joakin: Wizard. Save new network configuration

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#267]
The temp files are stored under /tmp but not yet SAVED to /etc/networks
This is required to comes in effect the changes after next reboot
Notice are two parts involved, one for wired and one for wifi ( wpa_supplicant call )

**Comment by orwellencarnation** [comment]
paste here the commit or the changes and then I will close it

**Comment by JFrancoJ** [comment]
New wizard.sh have been uploaded to root librerouter repo. 
This version saves the active network configuration to /etc/networks/interfaces , /etc/wpa/_supplicant.conf, /etc/init.d/start_wpasupllicant to prepare configurations for next reboot.
This version DOES NOT take care on recover network in the event WIFI , wire or internet router comes down and up.

**Comment by orwellencarnation** [comment]
Its fixed? do not forgot to put your name in the issue if it is asigned to you.

**Comment by JFrancoJ** [comment]
Yes , fixed on Apr 1
