### ISSUE TITLE
setup.sh script fails with message "Job for tor.service failed...."

### ISSUE THREAD

**Issue by jpocampor** [Librerouter/Librekernel#278]
Hi, I had trying many times to run the setup.sh script, and I try to resolve every error that shows in /var/libre_install.log, but now I have encountered with a Tor service error that implicates a fail service restart process.
Could you help me to understand this error?, then I could try fix this. I'll Attach the screenshots of this case. 
My test VM is Debian 8. 64bits, on Virtualbox. 

Thanks.
![config_6](https://cloud.githubusercontent.com/assets/6977526/24786900/685fff96-1b2a-11e7-8db5-7235f32d68de.png)

**Comment by jpocampor** [comment]
Hi, again.
The error were fixed, this issue are related with the defaults tor packages obtaining with single command 'sudo apt-get install tor'. I have encountered that if remove completely this tor installation to proceed with the second option available in the official tor site, the issue is solved.

**Tor Installation Guide:**
[https://www.torproject.org/docs/debian.html.en]

**Comment by orwellencarnation** [comment]
This is not the way we work
RCA
root cause analysis

And where is the patch?

**Comment by JFrancoJ** [comment]
Your last installation says:

You need at least 16GB of free space. Exiting


Your installation was failed.
Check your own logs 
You can get these logs at https://github.com/librereport/reports/blob/master/reports/report.17-04-07_09-21/libre_install.log

**Comment by jpocampor** [comment]
Yes, I agree, of course this is some that I will resolve, but in this case I have detected the issue in reference to Tor installation, and have relation with the Tor packages in the default repository, which should be replaced an executed according information in the Tor official web site. On the other hand, in this night I begin to resolve the space disk alert in my VM.
Thanks.
