### ISSUE TITLE
Joakin urgent Change ethx to bridge mode.

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#284]

**Comment by JFrancoJ** [comment]
:PREROUTING ACCEPT [223618:27299360]
:INPUT ACCEPT [221654:27179156]
:OUTPUT ACCEPT [328408:40156257]
:POSTROUTING ACCEPT [86544:6440731]
-A PREROUTING -d 217.148.71.240/32 -i eth1 -p tcp -j ACCEPT   se puede cambiar por -A   PREROUTING -d 217.148.71.240/32 -s 10.0.0.0/8 -p tcp -j ACCEPT


-A PREROUTING -d 217.148.71.165/32 -i eth1 -p tcp -j ACCEPT   idem
-A PREROUTING -d 217.148.69.240/32 -i eth1 -p tcp -j ACCEPT   idem
-A PREROUTING -d 217.148.69.165/32 -i eth1 -p tcp -j ACCEPT   idem
-A PREROUTING -d 192.229.182.219/32 -i eth1 -p tcp -j ACCEPT idem
-A PREROUTING -d 195.21.32.40/32 -i eth1 -p tcp -j ACCEPT       idem
-A PREROUTING -d 195.21.32.34/32 -i eth1 -p tcp -j ACCEPT       idem
-A PREROUTING -d 194.224.167.58/32 -i eth1 -p tcp -j ACCEPT   idem
-A PREROUTING -d 192.229.182.219/32 -i eth1 -p tcp -j ACCEPT idem
-A PREROUTING -d 10.0.0.11/32 -i eth1 -p tcp -j ACCEPT             idem
-A PREROUTING -d 10.0.0.12/32 -i eth1 -p tcp -j ACCEPT             idem
-A PREROUTING -d 10.0.0.238/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.239/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.240/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.241/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.242/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.243/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.244/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.245/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.246/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.247/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.248/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.249/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.250/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.251/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.252/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.253/32 -i eth1 -p tcp -j ACCEPT
-A PREROUTING -d 10.0.0.254/32 -i eth1 -p tcp -j ACCEPT          idem
-A PREROUTING -d 10.0.0.1/32 -i eth1 -p tcp -m tcp --dport 22 -j REDIRECT --to-ports 22
-A PREROUTING -d 10.0.0.1/32 -i eth1 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53  

Como llega un paquete con destion 10.x.x.x a otra interface que no sea la lan segura interna . Seria mas facil filtrar que no venga desde la lan hacia la lan ?

-A PREROUTING -d 10.0.0.1/32 -i eth1 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 80
-A PREROUTING -d 10.0.0.1/32 -i eth1 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 443
-A PREROUTING -d 10.191.0.1/32 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 3128           # squid
-A PREROUTING -d 10.191.0.1/32 -i eth1 -p tcp -m tcp --sport 80 -j REDIRECT --to-ports 3128   # squid
-A PREROUTING -d 10.0.0.0/8 -i eth1 -p tcp -m tcp --dport 22 -j REDIRECT --to-ports 9051
-A PREROUTING -d 10.0.0.0/8 -i eth1 -p tcp -j DNAT --to-destination 10.0.0.1:3129             # va al servicio squid
-A PREROUTING -i eth1 -p tcp -m ndpi  --http  -j REDIRECT --to-ports 3130

**Comment by orwellencarnation** [comment]
El iptables tiene que ser documentado por ti y por david , y tu le tienes que forzar a responder.

**Comment by JFrancoJ** [comment]
David Nikoghosyan wrote:
> Please have a look, I commented the lines you send me
>
> -A PREROUTING -d 217.148.71.240/32 -i eth1 -p tcp -j ACCEPT # Why LaCaixa IP here ?
> -A PREROUTING -d 217.148.71.165/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 217.148.69.240/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 217.148.69.165/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 192.229.182.219/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 195.21.32.40/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 195.21.32.34/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 194.224.167.58/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 192.229.182.219/32 -i eth1 -p tcp -j ACCEPT # Why this IP seems allowed to reach the lan from the wan
>
> above are some test bank ip addresses that should be accepted, like enrique said we should have all bank ip addresses here to allow direct connections.

ok,, I guess these rules are taken on murtaza . I asked Enrique if we can delete these rules from configuration-script
( the ones for banks )
>
> -A PREROUTING -d 10.0.0.11/32 -i eth1 -p tcp -j ACCEPT             # why no match -d and -s instead -i ? what you mean? -d is also used?
I mean as all traffic on eth1 is from 10.0.0.0/24 AND there NOT traffic on wlan ( expected on eth0 ) to destination 10.0.0.0/24
to match based on source net instead interface.
This apply for all similar rules
> -A PREROUTING -d 10.0.0.12/32 -i eth1 -p tcp -j ACCEPT

may be as:
-A PREROUTING -d 10.0.0.12/32 -s 10.0.0.0/8 -p tcp -j ACCEPT

and at the end the rest ( none of the following , will be redirected to squid ( see below )

> -A PREROUTING -d 10.0.0.238/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.239/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.240/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.241/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.242/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.243/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.244/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.245/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.246/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.247/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.248/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.249/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.250/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.251/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.252/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.253/32 -i eth1 -p tcp -j ACCEPT
> -A PREROUTING -d 10.0.0.254/32 -i eth1 -p tcp -j ACCEPT
>
> These are local services ip addresses, these addresses should also be accepted before we redirect traffic to squid.
>
> -A PREROUTING -d 10.0.0.1/32 -i eth1 -p tcp -m tcp --dport 22 -j REDIRECT --to-ports 22    // accept ssh comming from lan
change by:
-A PREROUTING -d 10.0.0.1/32 -s 10.0.0.0/8 -p tcp -m tcp --dport 22 -j REDIRECT --to-ports 22
>
> -A PREROUTING -d 10.0.0.1/32 -i eth1 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53 # Must probably filter all port 53 for not source lan  // accept dns comming from lan
> -A PREROUTING -d 10.0.0.1/32 -i eth1 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 80  // accept port 80
> -A PREROUTING -d 10.0.0.1/32 -i eth1 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 443   // accept port 443
> -A PREROUTING -d 10.191.0.1/32 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 3128           # squid  // Redirecting i2p
> -A PREROUTING -d 10.191.0.1/32 -i eth1 -p tcp -m tcp --sport 80 -j REDIRECT --to-ports 3128   # squid  // Redirecting i2p
> -A PREROUTING -d 10.0.0.0/8 -i eth1 -p tcp -m tcp --dport 22 -j REDIRECT --to-ports 9051 // ssh to tor socks proxy
> -A PREROUTING -d 10.0.0.0/8 -i eth1 -p tcp -j DNAT --to-destination 10.0.0.1:3129             # va al servicio squid // Redirecting tor traffic
change with :
-A PREROUTING -d 10.0.0.0/8 -s 10.0.0.0/8 -p tcp -j DNAT --to-destination 10.0.0.1:3129
> -A PREROUTING -i eth1 -p tcp -m ndpi  --http  -j REDIRECT --to-ports 3130 // Redirect http protocol to http squid
>
>

and so on ...
do you see any inconvenience ?

The goal is to avoid building bridge as is a little complex because user can change his network connections
after configuration-script and also configuration-script can not take in consideration the wifi's for wan nor lan
due don't ask user/installer for AP password.




>

**Comment by orwellencarnation** [comment]
Franco document in the readme as agreed!
