### ISSUE TITLE
Out of memory events in and after installation process for 2G RAM 512M swap on Debian8

### ISSUE THREAD

**Issue by vmspike** [Librerouter/Librekernel#286]
Attempt to install librerouter to clean Debian8 base system (only coreutils and ssh server) lead to OOM killer events in process of installation (after 2nd systemd line) and after it (after reboot, after 3rd systemd line):
```
root@librerouter:~$grep -e 'Started Apply Kernel Variables.' -e 'Out of memory:' /var/log/syslog{.1,}
/var/log/syslog.1:Apr  8 18:12:17 librerouter systemd[1]: Started Apply Kernel Variables.
/var/log/syslog.1:Apr  8 19:19:29 librerouter systemd[1]: Started Apply Kernel Variables.
/var/log/syslog.1:Apr  9 11:54:58 librerouter kernel: [15848.057724] Out of memory: Kill process 14004 (clamd) score 196 or sacrifice child
/var/log/syslog.1:Apr  9 12:00:05 librerouter kernel: [16155.613636] Out of memory: Kill process 13549 (java) score 136 or sacrifice child
/var/log/syslog.1:Apr  9 12:06:05 librerouter kernel: [16515.749697] Out of memory: Kill process 17343 (bundle) score 129 or sacrifice child
/var/log/syslog.1:Apr  9 12:06:05 librerouter kernel: [16515.755299] Out of memory: Kill process 17620 (util.rb:24) score 130 or sacrifice child
/var/log/syslog.1:Apr  9 12:25:16 librerouter kernel: [17662.716069] Out of memory: Kill process 17338 (bundle) score 108 or sacrifice child
/var/log/syslog.1:Apr  9 12:25:16 librerouter kernel: [17662.741595] Out of memory: Kill process 17338 (bundle) score 108 or sacrifice child
/var/log/syslog.1:Apr  9 12:25:16 librerouter kernel: [17662.752176] Out of memory: Kill process 17338 (bundle) score 108 or sacrifice child
/var/log/syslog.1:Apr  9 12:25:22 librerouter kernel: [17671.317073] Out of memory: Kill process 17338 (bundle) score 108 or sacrifice child
/var/log/syslog.1:Apr  9 12:52:12 librerouter kernel: [19279.723997] Out of memory: Kill process 15590 (Suricata-Main) score 98 or sacrifice child
/var/log/syslog.1:Apr  9 13:00:24 localhost systemd[1]: Started Apply Kernel Variables.
/var/log/syslog.1:Apr  9 13:09:32 localhost kernel: [20320.393460] Out of memory: Kill process 1920 (clamd) score 100 or sacrifice child
/var/log/syslog.1:Apr  9 13:25:15 localhost kernel: [21265.809082] Out of memory: Kill process 3383 (Suricata-Main) score 98 or sacrifice child
/var/log/syslog:Apr  9 13:38:20 localhost kernel: [22050.628533] Out of memory: Kill process 1970 (java) score 90 or sacrifice child
/var/log/syslog:Apr  9 14:18:23 localhost kernel: [24428.204073] Out of memory: Kill process 3485 (gitlab-mon) score 104 or sacrifice child
/var/log/syslog:Apr  9 14:18:23 localhost kernel: [24438.846417] Out of memory: Kill process 3485 (gitlab-mon) score 104 or sacrifice child
/var/log/syslog:Apr  9 14:18:23 localhost kernel: [24440.520889] Out of memory: Kill process 3485 (gitlab-mon) score 104 or sacrifice child
/var/log/syslog:Apr  9 14:18:23 localhost kernel: [24442.485001] Out of memory: Kill process 3485 (gitlab-mon) score 104 or sacrifice child
/var/log/syslog:Apr  9 14:18:23 localhost kernel: [24450.550042] Out of memory: Kill process 3485 (gitlab-mon) score 104 or sacrifice child
/var/log/syslog:Apr  9 14:18:23 localhost kernel: [24454.927192] Out of memory: Kill process 3485 (gitlab-mon) score 104 or sacrifice child
```
2nd installation attempt with 2G of swap works fine but extensively use swap (1750M RAM, 1850M SWAP) after installation.

So you either have to change requirements (e.g. initially check not only `RAM >= 2G` but `RAM+SWAP >= 4G`), or optimize environment for RAM usage (e.g. you can consider decrease wokers/threads number for some apps).

**Comment by JFrancoJ** [comment]
Please use only 8.7.1 amd64
Also paste dmidecode output and /proc/version here.
The RAM requirements have been moved to >1.9GB and runs fine on all platform tested until now.
SWAP is not checked , so you need at least 1900000 Bytes real RAM where you are trying with only 1.75G
I am configuring swap in different way as "usual" as more and more load are on low CPU performance hardware and ussing swap ( more noticiable on little machines with no SSD ) can cause many other issues ( slow down the librerouter )
Please try with at least 1.9GB REAL ram

**Comment by vmspike** [comment]
Used fresh Debian8.7.1 amd64 installed from netinst iso on Virtualbox 5 VM with Ubuntu 16.04 host with 2 core CPU and HDD.
Can send you archive with installation and oom logs if required.

This is screenshot form oom-free state (because of increased swap):
![screenshot at 2017-04-10 15 35 52](https://cloud.githubusercontent.com/assets/7644358/24878282/b4c1920c-1e5c-11e7-94aa-75c8aa7f8a40.png)
Librerouter seems laggy because of extensive swapping, even ssh connection can hang up for minute(s).

```
root@librerouter:~# cat /proc/version 
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07)
root@librerouter:~# dmidecode
# dmidecode 2.12
SMBIOS 2.5 present.
10 structures occupying 450 bytes.
Table at 0x000E1000.

Handle 0x0000, DMI type 0, 20 bytes
BIOS Information
	Vendor: innotek GmbH
	Version: VirtualBox
	Release Date: 12/01/2006
	Address: 0xE0000
	Runtime Size: 128 kB
	ROM Size: 128 kB
	Characteristics:
		ISA is supported
		PCI is supported
		Boot from CD is supported
		Selectable boot is supported
		8042 keyboard services are supported (int 9h)
		CGA/mono video services are supported (int 10h)
		ACPI is supported

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: innotek GmbH
	Product Name: VirtualBox
	Version: 1.2
	Serial Number: 0
	UUID: D4E7B4C3-6B9F-4AE5-B841-38FB67BF9E58
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Virtual Machine

Handle 0x0008, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: Oracle Corporation
	Product Name: VirtualBox
	Version: 1.2
	Serial Number: 0
	Asset Tag: Not Specified
	Features:
		Board is a hosting board
	Location In Chassis: Not Specified
	Chassis Handle: 0x0003
	Type: Motherboard
	Contained Object Handles: 0

Handle 0x0003, DMI type 3, 13 bytes
Chassis Information
	Manufacturer: Oracle Corporation
	Type: Other
	Lock: Not Present
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: None

Handle 0x0007, DMI type 126, 42 bytes
Inactive

Handle 0x0005, DMI type 126, 15 bytes
Inactive

Handle 0x0006, DMI type 126, 28 bytes
Inactive

Handle 0x0002, DMI type 11, 7 bytes
OEM Strings
	String 1: vboxVer_5.0.32
	String 2: vboxRev_112930

Handle 0x0008, DMI type 128, 8 bytes
OEM-specific Type
	Header and Data:
		80 08 08 00 70 67 1B 00

Handle 0xFEFF, DMI type 127, 4 bytes
End Of Table
```

**Comment by JFrancoJ** [comment]
As you got several "out of memory" I would recommend to use at least 1.9G RAM ( with or without swap )
as process have been aborted due lack of memory and then all these strange errors can happen.
Anywise swap utilization on installation-script.sh and configuration-script.sh must not cause too much lag in you ssh session. 
I checked your Debian version and is same as mine and other guys. 
Once no any "out of memory" errors there, the next cause may be that virtual have not eth0/eth1 ( may be other names ). Check udev for naming, as installation-script.sh is a bit stupid and only likes eth0 and eth1.
There other errors that are not important if no some file is found as will be created ( as /var/run/cron/.../root) , but most of files you have reported are missed, must NOT be missed and means the task was aborted inside the call of installation_script, and you are right, not all errors are sent to logs, so is much better to watch the screen for these class of errors.

**Comment by orwellencarnation** [comment]
We would need noswap off as requirement?
What you need to fix it? you are the expert...supossely
How you plan to debug it?

**Comment by vmspike** [comment]
@JFrancoJ , as you can see I've used 2GiB RAM in both cases, but first one with 512MiB SWAP lead to OOM killer events during installation and after it (after reboot), 2nd one with 2GiB SWAP had no OOM events but laggy, because almost all RAM and SWAP are full, while it's clean installation.
SSH session hangs up after some time after [re]boot (haven't touch it on installation), then when all processes already started (and swapped), ssh connection became alive.

> I checked your Debian version and is same as mine and other guys.
> Once no any "out of memory" errors there, the next cause may be that virtual have not eth0/eth1 ( may be other names ). Check udev for naming, as installation-script.sh is a bit stupid and only likes eth0 and eth1

There're eth0 and eth1 only. As I said no oom events occurs with 2GiB swap (another separate errors not related to oom reported in [issue 287](https://github.com/Librerouter/Librekernel/issues/287)).

> is much better to watch the screen for these class of errors

Installation (since run setup.sh to auto reboot) took ~4.5h on my VM, so it's hard to watch the screen all this time :). Because of this I've used redirect (via `tee`) to the file.

I see that app-installation-script.sh check for RAM size, so I suggest to add check for RAM+SWAP size.
You see in `htop` screenshot above that clean installation takes 1766MiB RAM + 1869 MiB SWAP.
OOM events during installation can be avoided by not automatically start just setup services before reboot, but you still have to increase ram+swap requirements OR optimize services, e.g. decrease numbers of workers/threads for some of them (java, apache, nginx, etc).

Also it could be good idea to pack packages which you build from sources to deb packages. It significantly decrease installation time and could be easier for you to support. You still can keep an option to build them from sources if user want it.

**Comment by JFrancoJ** [comment]
Hi Mikhail

I guess you are the only faccing OOM on your box.
There other guy also ussing Virtualbox and as long as I know he didn't 
face it, but I don't know his Virtualbox enviroment.
Also I already installed several times in other VM ( Debian 8.7.1 on 
Proxmox, 2GB RAM, 32GB HD ) and faced not OOM
I also installed on Qotom with just 19xx KRAM without OOM.
Adding check on RAM+Swap is not  so good, as you say the system comes 
lagged and probably working on Swap must
be as last resource and in very special case or events, but never as 
usual or your librerouter will ends clogged.
One thing you must check, even you setted your VM with some memory that 
there enough free memory in the host
to allocate for your VM, may be other VMs eats much RAM

Some of the errors you reported are not critical errors, like some 
missed file, when the installation-configuration checks
for this file, and if is not there then install it. Tipically on each if 
[ -e $file ] , as the stderr have been not redirected you will
see these errors.

Yes, you are right, installation-configuration takes so long that is 
hard to watch and hard to get enough time in a day
to try several full installations from scratch.
We are working also in this way, as is causing our project development 
comes annoying
If you check other issues you will see some of them related to 
unattended installation as well as Librerouter repository.

Probably you have observed we compile from sources some things, as 
Atheros firmware, that takes a longgggggg
time to compile, but this is due the repo for this firmware doesn't 
works, and the official Debian repository puts these
free code inside the global non-free pack. These class of things are 
going to be fixed once we have our own repository.

About load on each engine, there also an open #issue about to detect 
load do "nice" on each engine moving to low
priority some process, and may also  "ulimit" for that task.
Playing with CPU throttle may be avoided due this caused other problems 
in some platforms ( for now only on Qotom )

First of all I would try to re-config your VM with ballons or more RAM 
and  try if OOM gone. While OOM the folked tasks
from installation-configuration fails and then all your box go on very 
unstable configuration.


Mikhail Vagin wrote:

**Comment by orwellencarnation** [comment]
Did you tested with 4 gb of ram or with 3gb?

**Comment by vmspike** [comment]
I've tested two configurations:
2GiB RAM + 512MiB SWAP -> OOM
2GiB RAM + 2GiB SWAP -> Fine but laggy sometimes

**Comment by orwellencarnation** [comment]
No swap! Franco agree?

**Comment by JFrancoJ** [comment]
depends ...

On installation and/or configuration 2GB physical RAM is required. If 
2GB then swap or not swap no matter.
On production stage always providing some swap will save you of full 
system dead due out of memory, at cost of speed.
The rule is not yes or not swap, is to provide at least 2GB physical RAM
The scenario seems affects only VM


orwellencarnation wrote:

**Comment by vmspike** [comment]
Even if you suppose that my configuration is wrong, OOM is my fault only and 2GiB RAM is enough for stable work generally it's better to have swap (if it's not located on sd/flash card), but to avoid extensive swap usage just decrease sysctl vm.swappiness to 1 or even 0
From `man proc`:
```
/proc/sys/vm/swappiness
       The  value  in this file controls how aggressively the kernel will swap memory pages.
       Higher values increase aggressiveness, lower values decrease aggressiveness.
       The default value is 60.
```
