### ISSUE TITLE
Disk encryption  froze installation

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#295]
root       570  0.0  0.1  63316  3020 tty1     Ss   19:31   0:00 /bin/login --
root       851  0.0  0.2  22996  5112 tty1     S    19:31   0:00  \_ -bash
root       994  0.0  0.1  13316  3148 tty1     S+   20:58   0:00      \_ /bin/bash ./setup.sh
root      1001  0.0  0.2  14784  4632 tty1     S+   20:58   0:00          \_ /bin/bash ./app-installation-script.sh
root      1199  3.2  1.8  71720 35716 tty1     S+   20:59   1:07              \_ apt-get -y --force-yes install ntp ntpdate
root      1297  0.0  0.2  18476  4232 pts/1    Ss+  20:59   0:00                  \_ /usr/bin/dpkg --status-fd 19 --configure libopts25:amd64 ntp:amd64 ntpdate:amd64 lockfile-progs:amd64
root      1302  0.0  0.0   4336  1576 pts/1    S+   20:59   0:00                      \_ /bin/sh /var/lib/dpkg/info/ntp.postinst configure
root      1350  0.0  0.0   4336  1520 pts/1    S+   20:59   0:00                          \_ /bin/sh /usr/sbin/invoke-rc.d ntp start
root      1381  0.0  0.1  22488  2456 pts/1    S+   20:59   0:00                              \_ systemctl start ntp.service
root      1383  0.0  0.0  13180  1788 pts/1    S+   20:59   0:00                                  \_ /bin/systemd-tty-ask-password-agent --watch

Seems like is prompt for password, but screen says nothing, just "ntp .." 
Then if you at blind enter your disk password the installation continues.

**Comment by JFrancoJ** [comment]
This happens again and again, seems like randomly on many PID while installation.
Can we do : 
systemctl stop systemd-ask-password-wall.service  ?

**Comment by orwellencarnation** [comment]
What does this command?
