### ISSUE TITLE
David: grub update causes conficts with some cryptodevices installed on base Debian

### ISSUE THREAD

**Issue by JFrancoJ** [Librerouter/Librekernel#297]
Do not modify /boot/grub/* files , otherwise you can come on many errors on next boot, due lost of found partition, and also the initrd you placed as default doesnt have cryptsetup, so the only way to recover the system is booting from external device and repair grub.cfg and use other initrd with cryptsetup

Please remove the function that modifies grub in configuration-script and confirm.

**Comment by orwellencarnation** [comment]
It upgrading grub only reason?

**Comment by nikdavnik** [comment]
the function was adding one command for thermal warning in grub configuration and then updating it.
I removed it. commited

**Comment by JFrancoJ** [comment]
I rechecked and think you can close this issue once grub.cfg is not modified on installation/configuration as the defaul grub.cfg from debian installa works fine and has the right initrd

**Comment by JFrancoJ** [comment]
yes.

orwellencarnation wrote:
