### ISSUE TITLE
Edge browser direct search in the browser by word redirect to yacy blank in hiden tor

### ISSUE THREAD

**Issue by pastafaarian** [Librerouter/Librekernel#43]
If you try to write in microsoft edge a keyword in the browser
Instead of redirecting to yacy and search for the word 
Is goin yacy by it hidden service

Should be not going to hiden but direct local service
Should be just changing the hostname by yacy 

Who is doint this problem?
A wireshark captures shows that any bing request go yacy by tor

**Comment by kiktr0n** [comment]
http://www.google.de/search?q=sevilla
need to be
http://yacy.librenet/yacysearch.html?query=sevilla
