### ISSUE TITLE
Webrtc working?

### ISSUE THREAD

**Issue by pastafaarian** [Librerouter/Librekernel#44]
Is going to work by TOR for the external user?
Why is not asking for permissions in some browser?

**Comment by nikdavnik** [comment]
It's working file in firefox v47.
Tried  chrome v52, not working. 
Opened browsers as super user (sudo) but didn't help.

**Comment by nikdavnik** [comment]
easyrtc is fixed.
For audio and video connection there was a need to have a https server, so I moved http://easyrtc.librenet to https://easyrtc.librenet and it worked.

**Comment by mogolo** [comment]
The user should go https://easyrtc.librenet/demos/demo_audio_video_simple.html
by onion and he needs to share with other user his onion. This is the only services he needs to go onion at least to knw which url to share with the other people via email.

**Comment by mogolo** [comment]
Error messages
Unable to reach the EasyRTC signalling server.

**Comment by nikdavnik** [comment]
Issue is fixed. I moved easyrtc to ssl mode, 
also added easyrtc.setSocketUrl(":8443"); in servers js files.

This issue can be closed

**Comment by nikdavnik** [comment]
EasyRTC works fine. This issue can be closed.
