### ISSUE TITLE
Issues Suricata Tunning de bumped traffic

### ISSUE THREAD

**Issue by pastafaarian** [Librerouter/Librekernel#49]
The 2 squids with bumping are using iccap and upstream proxy port.

Al signatures for http and https in snort and suricata should be applied for this 2 ports.

A part of that the rest of non httpo and https signatures should be applied as usual to all traffic reaching the client pcs.

**Comment by orwellencarnation** [comment]
update?

**Comment by orwellencarnation** [comment]
evidence of suricata is reading debumped deciphered traffic?
