### ISSUE TITLE
appconfiguration script ends or not ends in the proper way

### ISSUE THREAD

**Issue by kiktr0n** [Librerouter/Librekernel#55]
The console do not appears, does the script finished or not?

**Comment by nikdavnik** [comment]
Script was finishing in mailpile console. That was the result of mailpile, which requires interactive console to run.
I changed mailpile starting command 
from
/opt/Mailpile/mp
to 
/usr/bin/screen -dmS mailpile_init /opt/Mailpile/mp
Now no interactive console is needed so script finishes in normal shell.
