### ISSUE TITLE
Be sure all the password in any script are move to app configuration script and dinamically generated

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#58]
Be sure all the password in any script are move to app configuration script and dinamically generated

**Comment by k1ktr0n** [comment]
http://www.makeuseof.com/tag/5-ways-generate-secure-passwords-linux/

**Comment by petrskovoroda** [comment]
MySQL password setting moved to configuration script
Commits: e0e42566afbf60b417023a507fc91d5f8f362fe9 and 9e51ece1e4a576bac7c0300efe5ded077e54c2e3

**Comment by nikdavnik** [comment]
At this moment all passwords are generated in configuration script.
I close the issue
