### ISSUE TITLE
Export the hsts domain list from major browsers to create a domain list

### ISSUE THREAD

**Issue by pastafaarian** [Librerouter/Librekernel#61]
All this domains need to go through the new solution purposed to bypass hsts: dns2proxy,ssltrip,bettercap, etc.

The rest of the domains should use another path in the proxies.

The good domains like all banks should not go through either hsts or bumping but direct.

**Comment by nikdavnik** [comment]
We decided to create our browser to bypass hsts. So this issue is not actual anymore and can be closed.

**Comment by nikdavnik** [comment]
you can find HSTS full list at
https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json

googlr, firefox, chromium and others are using this one
