### ISSUE TITLE
app-installation-script.sh. http://ftp.es.debian.org not accessible for me. I change it to http://ftp.debian.org

### ISSUE THREAD

**Issue by mistralbkru** [Librerouter/Librekernel#66]
http://ftp.es.debian.org not accessible for me. I change it to http://ftp.debian.org

lines 208 and 209 
		echo "deb http://ftp.es.debian.org/debian/ jessie main" > /etc/apt/sources.list
		echo "deb http://ftp.es.debian.org/debian/ jessie-updates main" >> /etc/apt/sources.list

/tmp/apt-get-update-default.log :
Hit http://security.debian.org jessie/updates InRelease
Err http://ftp.es.debian.org jessie InRelease

Err http://ftp.es.debian.org jessie-updates InRelease

Err http://ftp.es.debian.org jessie Release.gpg
  Unable to connect to ftp.es.debian.org:http:
Err http://ftp.es.debian.org jessie-updates Release.gpg
  Unable to connect to ftp.es.debian.org:http:
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://security.debian.org jessie/updates/main Translation-en
Reading package lists...

**Comment by nikdavnik** [comment]
New repository  http://ftp.debian.org/debian works fine. The issue can be closed
