### ISSUE TITLE
issues in the latest version of app installation script 7 sept 2016

### ISSUE THREAD

**Issue by k1ktr0n** [Librerouter/Librekernel#67]
W: Failed to fetch http://ftp.us.debian.org/debian/dists/jessie/main/source/Sources  404  Not Found [IP: 128.61.240.89 80]

W: Failed to fetch http://ftp.us.debian.org/debian/dists/jessie/main/binary-i386/Packages  404  Not Found [IP: 128.61.240.89 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

Updating repositories ...
W: Failed to fetch http://ftp.es.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://ftp.es.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://ftp.es.debian.org/debian/dists/jessie/Release.gpg  Unable to connect to ftp.es.debian.org:http:

W: Failed to fetch http://ftp.es.debian.org/debian/dists/jessie-updates/Release.gpg  Unable to connect to ftp.es.debian.org:http:

W: Some index files failed to download. They have been ignored, or old ones used instead.
Installing apt-transport-https ...
E: Unable to locate package apt-transport-https
Error: Unable to install apt-transport-https

**Comment by nikdavnik** [comment]
I have changed repository to  ftp.debian.org

New source list
deb http://ftp.debian.org/debian jessie main contrib non-free
deb http://ftp.debian.org/debian jessie-updates main contrib non-free
deb http://security.debian.org jessie/updates main contrib non-free
deb http://ftp.debian.org/debian jessie-backports main contrib non-free
deb-src http://ftp.debian.org/debian jessie main contrib non-free
deb-src http://ftp.debian.org/debian jessie-updates main contrib non-free
deb-src http://security.debian.org jessie/updates main contrib non-free
deb-src http://ftp.debian.org/debian jessie-backports main contrib non-free

**Comment by nikdavnik** [comment]
New repositories works fine, The issue can be closed
