### ISSUE TITLE
Error in installation script error

### ISSUE THREAD

**Issue by waituru** [Librerouter/Librekernel#69]
These are challenges experienced when installing Librekernel on a clean Debian Jessie(8.5) virtual machine

Public key - 1460252357 has expired. This prevents the apt-get update command from running to  completion
(Quick fix is alter time on local machine to an early date)

Debian 8.5 lacks all the required repositories for the installation script to complete. I have added wheezy repositories but this has only reduced the number of packages that couldn't be found.
the ones remaining are;

1. virtualenv
2. php-zeta-caonsole-tools
3. libjpeg62-turbo-dev
4. python-pgpdump
5. libndpi-bin
6. libfixbuf3
7. libgb-perl

**NB**virtulaenv and libgb-perl lack installation candidates

**Comment by nikdavnik** [comment]
Debian repositories in updated in the last commit. Please try again

**Comment by waituru** [comment]
it has reduced the number of packages that can be found.
only roundcube cant be located

**Comment by nikdavnik** [comment]
Please test the last commited version in fresh debian 8.
It work ok for me. All packages are being succesfully installed

**Comment by waituru** [comment]
did that but now it keeps on failing at line 855 libecap file not found and 857 ./configure not found

**Comment by k1ktr0n** [comment]
what your email?

**Comment by waituru** [comment]
waituru@live.com

**Comment by nikdavnik** [comment]
Waituru, please make sure you are using the lastest commited version

**Comment by waituru** [comment]
Hi,


Squid fails to install with the new commit.


Please see in attachment.


with regards,
Waituru Mwangi


________________________________

**Comment by nikdavnik** [comment]
Waituru, I tested squid installation, it passed succesfully.
Please send me your outpul

Regard
David

**Comment by k1ktr0n** [comment]
Waituru there i sno attachment
