### ISSUE TITLE
Need to move save_variables to app-configuration-script.sh

### ISSUE THREAD

**Issue by SibirskiyVolk** [Librerouter/Librekernel#78]
We need to make the installation script machine independent so that we can run it inside the chrooted environment in order to create a rootfs for the iso build.

Starting by moving the save_variables() to configuration script, and have the configuration script detect all the machine variables "the OS type could still reside in the installation script and shouldn't cause any trouble inside the chroot jail"

Is there any problem with that @nikdavnik ?!

**Comment by nikdavnik** [comment]
As I understand you just need 2nd script to detect variables inself

for this, move these functions into begining of 2nd script.
get_platform()
get_hardware()
get_interfaces()

and comment get_variables() function in 2nd script.

no need to move save_variables() function

**Comment by SibirskiyVolk** [comment]
@nikdavnik 
Take a look at these modifications and tell me if it's okay for you
https://github.com/Librerouter/Librekernel/blob/gh-pages/01-app-installation-script.sh
https://github.com/Librerouter/Librekernel/blob/gh-pages/00-app-configuration-script.sh

The installation script runs well inside the chroot() and it has been used to produced this isofs
http://i386.sphinux.org/LibreRouter_8.6a0.1_i386.7z

@samy-mohsen  is testing the isofs so don't bother for now to test the iso, just test the scripts by running them and confirm that all services run as they did before the modifications.

Regards

**Comment by nikdavnik** [comment]
in this scenario installation script will fail, DO NOT change anything in
installation script.

just copy past following functions from installation script into
configuration script(put them after or before get_variables function, and
comment get_variables function invoice)
get_platform()
get_hardware()
get_interfaces()

**Comment by SibirskiyVolk** [comment]
Did you check the scripts I posted ?! they just do what you said.

**Comment by nikdavnik** [comment]
yes I checked your scripts, you changed more than I said

**Comment by SibirskiyVolk** [comment]
I did comment parts of the configure_bridge function since this should occur after the installation, should it be enabled at the installation time ?

**Comment by nikdavnik** [comment]
Please left it in installation script. We needn't this function right not
in configuration script neither in installation script.

**Comment by SibirskiyVolk** [comment]
okay, will do that in the next commit

**Comment by nikdavnik** [comment]
2 scripts are seperated
