### ISSUE TITLE
urgent Need to comment on added packages to the basepacks file for the isofs creation

### ISSUE THREAD

**Issue by SibirskiyVolk** [Librerouter/Librekernel#79]
Dear @nikdavnik 
We need to add all preinstalled packages from the debian repository only for the isofs into basepacks file: 
https://github.com/Librerouter/Librekernel/blob/gh-pages/isobuild/env/basepacks
instead of installing them from the installation script, and comment on each package with justification for why we need them (dependency of what) ... this would help us control the garbage dependencies and organize the project (docs).

please note that only packages from the debian repository set in the configuration file of the buildscript
https://github.com/Librerouter/Librekernel/blob/gh-pages/isobuild/env/config
which in our case is:
"deb http://ftp.debian.org/debian jessie main contrib non-free" should be added, not even jessie-updates.

other packages shall remain in the installation script.

**Comment by orwellencarnation** [comment]
david update on this matter
