### ISSUE TITLE
The package "gitlab" doesn't work on i386 architecture.

### ISSUE THREAD

**Issue by samy-mohsen** [Librerouter/Librekernel#81]
@nikdavnik After running the installation script, I've found an error with the package "gitlab". After some investigation, it turned out that the package "gitlab" supports only amd64 architecture. Please, add a condition that checks the system's architecture to the installation script before trying to install gitlab.

**Comment by nikdavnik** [comment]
gitlab can only be installed on amd64 machine.
I will comment gitlab installation will we find a solution for this

solutions can be
1. adjust installation condition that the machine must be 64bit
2. find another alternative (can be git )

**Comment by mogolo** [comment]
option 1 

when the machine is 64 then gitlab will be installed 

1. adjust installation condition that the machine must be 64bit 

El 2016-10-18 09:05 PM, nikdavnik escribió:

> gitlab can only be installed on amd64 machine.
> I will comment gitlab installation will we find a solution for this 
> 
> solutions can be
> 1. adjust installation condition that the machine must be 64bit
> 2. find another alternative (can be git ) 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/Librerouter/Librekernel/issues/81#issuecomment-254607258
[2]

**Comment by nikdavnik** [comment]
I add script to check hardware architecture
if x86_64 it installs gitlab
if something else it just skips gitlab installation
