### ISSUE TITLE
installation script is not comleting as gitlab is not getting installed

### ISSUE THREAD

**Issue by dbavale** [Librerouter/Librekernel#82]
not able to locate the package gitlab-ce

**Comment by nikdavnik** [comment]
gitlab can only be installed on amd64 machine.
I will comment gitlab installation will we find a solution for this

solutions can be
1. adjust installation condition that the machine must be 64bit
2. find another alternative  (can be git )

**Comment by nikdavnik** [comment]
duplicate issue #81.
Will close this one
