### ISSUE TITLE
easyrtc_server_example.zip is no longer available

### ISSUE THREAD

**Issue by SibirskiyVolk** [Librerouter/Librekernel#86]
https://easyrtc.com/assets/files/easyrtc_server_example.zip url used by installation script gives 404 not found.
which makes installing easyrtc not possible

cd /opt/easyrtc/
npm install

npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.12.101-1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.48                        
npm ERR! npm v2.15.1                       
npm ERR! path /opt/easyrtc/package.json
npm ERR! code ENOPACKAGEJSON                                      
npm ERR! errno 34
npm ERR! package.json ENOENT, open '/opt/easyrtc/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! Please include the following file with any support request:
npm ERR!     /opt/easyrtc/npm-debug.log

@nikdavnik

**Comment by dbavale** [comment]
I am getting the same error. File not found...

**Comment by nikdavnik** [comment]
Fixed.
