### ISSUE TITLE
20 Moving home partition of owncloud and tahoe to external hdd or bigger  if only one

### ISSUE THREAD

**Issue by SibirskiyVolk** [Librerouter/Librekernel#89]
@nikdavnik Please modify your script to setup the home partition of services that does storage locally to an external secondary disk like hdd or sdcard 
thank you

**Comment by k1ktr0n** [comment]
make the script to detect a second harddisk then move owncloud
data home and Tahohe lafs backup home to external harddisk no ssd if
exists (the scripts need to check how many harddisk exists)

**Comment by orwellencarnation** [comment]
https://github.com/Librerouter/Librekernel/blob/gh-pages/MagicBackup.md
a)Install tahoe , run 2 instances
b)adjust 1 for tor another for i2p with existing proxies
c)make a script that backup all config files and dbs and home from 
owncloud to both grid in private space
d)generate password for encrypt tahoe private space keys in public 
space.
e)zip with 20charater pass the keys in taohe both in public space with 
public introducers and nodes.
f)store ziped in owncloud admin home
test and modify the doc in the link
