### ISSUE TITLE
solution for private certificate in browser not giving warnings

### ISSUE THREAD

**Issue by samy-mohsen** [Librerouter/Librekernel#91]
Whenever I access a website with https (HSTS or not) It returns a warning message with code NET::ERR_CERT_AUTHORITY_INVALID. 

and as a result the following websites do not work by direct access neither redirection:

owncloud.librenet
mailpile.librenet
friendica.librenet
easyrtc.librenet
webmin.librenet

**Comment by samy-mohsen** [comment]
I have also tried to access the examples from the testing file ( https://owncloud.org/ and https://way.com/) but was given the same response.

Although when I tried to access https://www.caixabank.com/ it loaded the page with no problems,

**Comment by k1ktr0n** [comment]
samy lets have a session together : eric ping me in IM

**Comment by samy-mohsen** [comment]
@k1ktr0n done

**Comment by nikdavnik** [comment]
related to #99
