### ISSUE TITLE
URGENT DAVID Implement NDPI for https and http

### ISSUE THREAD

**Issue by orwellencarnation** [Librerouter/Librekernel#92]
Document about how to sent to David

**Comment by nikdavnik** [comment]
ndpi is installed

**Comment by nelsongnza** [comment]
Running Virtual Machine VirtualBox 5.1.4r110228. Debian 8. Installed gwak, gcc, build-essential, libpcap, libntop, libpcap, libndpi, pcapReader. Everythings Ready for config file and So...

**Comment by k1ktr0n** [comment]
nelson read davids coment above!

**Comment by k1ktr0n** [comment]
http://thingsinlinux.blogspot.ch/2016/02/installing-and-configuring-ndpi.html

**Comment by orwellencarnation** [comment]
david document here the kernel panic

**Comment by nikdavnik** [comment]
I installed new version of ndpi from https://github.com/vel21ripn/nDPI,
it seems working fine,

**Comment by orwellencarnation** [comment]
Evidence of it:
Capture in client,librerouter tcpdump that shouws traffic is diverted properly
