### ISSUE TITLE
I2p Websites do not work . sammy where  is the evidence?

### ISSUE THREAD

**Issue by samy-mohsen** [Librerouter/Librekernel#97]
All onion websites listed by executing `services` do not work and give away "Sitio web inalcanzable" which is spanish for "Site unreachable". The problem is (obviously) with I2p configurations.

The only i2p website that functions is "http://stats.i2p/"

**Comment by k1ktr0n** [comment]
samy do me a favour paste evidence and logs about all the issues your rising and make the test document better like a checklist
