### ISSUE TITLE
Bypassing SSL private cert. warning method no.1

### ISSUE THREAD

**Issue by SibirskiyVolk** [Librerouter/Librekernel#98]
@nikdavnik 
as @k1ktr0n suggested, we may need a method to bypass the browser warning about the private ssl certificate being used by us for https connections.
here's the first method:

Design a software / script that the user need to run on client machine that does install the private ssl certificate on his client OS and accept Librerouter as a valid CA
Make sure that this script / software is portable enough to run on most commonly used Operating systems (MS-Win / OSX / GNU/Linux / Android / iOS / Windows Phone)

this would of course require hiring developers for such platforms, and for platforms like Android, I suspect that it would accept doing that without having a rooted device (same for iOS except it's jailbreak) ... so we need experts for those platforms

**Comment by k1ktr0n** [comment]
This will be part of the corpbypass solution 
https://github.com/Librerouter/Librekernel/blob/gh-pages/Corp-bypasser.md
