### ISSUE TITLE
Bypassing SSL cert. warning method no. 2

### ISSUE THREAD

**Issue by SibirskiyVolk** [Librerouter/Librekernel#99]
@nikdavnik 
as @k1ktr0n suggested, we may need a method to bypass the browser warning about the private ssl certificate being used by us for https connections.
here's the second method:

Instead of using domian service.librerouter we use service.librerouter.com while purchasing a wildcard ssl certificate for domain librerouter.com and install the root certificate pem on the librerouter device.

Personally I prefer this method since it's more realistic and has less compatibility hassle

**Comment by k1ktr0n** [comment]
Tell which kind of certificate I need for creating multidomains:

For creating:

serviceX.librerouter.net

David wont be anymore librerouter or librerouter.local

global domains will be resolving local private IPs

conferencing.librerouter.net  -------> 10.0.0.25X

Now we are going to install a multidomain global certificate in ALL librerouter machines.

Question I have is

I found>

With green bar verification
EV
with local domains
with SAN

Could you tell me which one we need to make the browser no to give the private certificate warning.

**Comment by SibirskiyVolk** [comment]
I recommend this
https://cheapsslsecurity.com/comodo/positivessl-wildcard.html

**Comment by k1ktr0n** [comment]
Why this one and no other features? like multidomain or EV, or green bar or "local domain" or SAN?

**Comment by nikdavnik** [comment]
Hi,

Here is my opinion.

about certificates
There are several types of SSL Certificates, and we can group SSL
certificates by validation level or secured domains/hostnames.

*Validation levels:*
*1.Domain Validated SSL Certificates*
The Domain Validated SSL Certificate validates the domain is registered and
someone with admin rights is aware of and approves the certificate request.
The validation process is normally performed via email or DNS
*2. Organization Validated SSL Certificates*
The Organization Validated SSL Certificate (OV certificate) validates the
domain ownership, plus organization information included in the certificate
such as name, city, state and country.
*3.Extended Validation SSL Certificates*
The Extended Validation SSL Certificate (EV certificate) requires an
extended validation of the business. It validates domain ownership and
organization information, plus the legal existence of the organization.

*SSL Certificates by Secured Domains*
*1.Single-name SSL Certificates*
Single-name SSL certificates protects a single subdomain. For example, if
you purchase a certificate for www.example.com it will not secure
mail.example.com.
*2.Wildcard SSL Certificates*
A wildcard certificate can secure an unlimited number of first level sub
domains on a single domain name. For example, you could get a wildcard
certificate with *.yourdomain.com as the common name. This certificate
would secure www.yourdomain.com, mail.yourdomain.com, secure.yourdomain.com,
anything.yourdomain.com, etc…
*3. Multi-Domain SSL Certificates (or SAN)*
Multi-domain SSL certificates protect different domains with a single
certificate. For Example you can protect www.yourdomain.com,
www.something.com. Mail.server.com etc.

*Ev or green bar*
Ev or green bar is only when you have passed Extended Validation, i.e.
validation of domain ownership, organization information and legal
existence of the organization

All certificates are providing the same security level

---------------------------------------------------------------------------------------------------------------

According to this we need Wildcard SSL Certificates. This certificates can
be purchased for given number of subdomains, in our case I thing we need
for up to 10-15 subdomains, and we also need it to be signed for different
ip addresses as our subdomains are using different ip addresses.


*Now about disadvantages.*

*1.* This will not solve HSTS problem.
*2*. At first we need to own domain, and only after that we can issue
certificated signing for that domain. (Do we own domain librerouter.ner? Or
something like that)
And if we want to issue certificate for local domain it will not be
possible,  As I know it is not possible to issue certificate signing for
local (private domains, for example librerouter.local) starting from
November 1, 2015.
*3*. We need to spend money, for domain purchase and for wildcart
certificate. Minimum $200-300 for 1 year.
*4*. what will happen after 1 year. Who will update certificates and
domains.
*5*. Who will update certificates on already selled librerouters.
*6*. We do not need this rigth now(spend money, purchase certificates), we
will need it when everthing will be ready, purchasing certificate will take
1 week it’s not a problem, also by that time we may came to other solution
as this one is not working for us.


*Possible Solution for this problem.*

Right now I can see only one solution. Macking browser with preinstalled CA.
It’s cheap, no additional spendings,
it’s fase, as it can be firefox with preinstalled root CA
it’s permanent


Regards,
David

**Comment by SibirskiyVolk** [comment]
@k1ktr0n 
why do you need multidomain ?! are you going to use another domain that *.librerouter.com ?
Why Extended Validation and green bar ?! are you going to use it for ecmmerce ?! also greenbar requires lots of paperworks for a company.
